locations = [
    "Madhapar Chowk",
    "Ayodhya Park Chowk",
    "Shital Park",
    "Ramdevpir Chowk",
    "Nanavati Chowk",
    "Raiya Chowk",
    "Raiya TelePhone Exchange",
    "Indira Circle",
    "West Zone Office",
    "Nana Mava Chowk",
    "Maha Puja Dham Chowk",
    "Om Nagar Chowk",
    "Mavdi Chowk",
    "Umiya Chowk",
    "Ambedkar Chowk",
    "Goverdhan Chowk",
    "Punit Nagar Chowk",
    "Gondal Chowk",
    "Saurashtra University",
    "BT Savani (Kidni) Hospital",
    "Akashvani Chowk",
    "Panchayat Nagar Chowk",
    "Indira Circle",
    "Indubai Mahasatiji Chowk",
    "Swaminarayan Mandir / Mahila",
    "Astron Chowk",
    "Hemu Gadhvi Hall",
    "Ramkrushna Aashram",
    "Malaviya Chowk",
    "Trikon Baug",
    "HN Shukla College",
    "Pradyumna Park",
    "Marketing Yard",
    "Bhagirath Society",
    "Lakheshvar Society - R.T.O. Office",
    "GramUdhyog Mandir Pedak",
    "Setellite Chowk - Maruti Nagar Approach Road",
    "Aayaknagar - Pedak Road",
    "Narayan Nagar Approach Road - Govind Nagar",
    "Champak Nagar - Panino Ghodo",
    "Patel Vadi",
    "Parevadi Chowk",
    "Hospital Chowk",
    "Trikon Baug",
    "Malaviya Chowk",
    "Ramkrushna Aashram",
    "Dharmendrasihnji College",
    "Jilla Panchayat Chowk",
    "Kishanpara Chowk",
    "Swaminarayan Mandir / Mahila",
    "Indubai Mahasatiji Chowk",
    "Indira Circle",
    "Panchayat Nagar Chowk",
    "Sadhu Vasvani School",
    "Ajanta Park / Janak Puri",
    "Balaji Park / Satellite Park",
    "Aalap Green City",
    "Raiya Gam",
    "Jivraj Park",
    "Aarya Land Residency",
    "Jetko Chokdi",
    "Dream City",
    "Mavdi Gam",
    "Mavdi Chowk",
    "Fuliya Hanuman Mandir",
    "Mavdi Fire Station",
    "Aanand Bunglows",
    "Swaminarayan Chowk",
    "P. D. M. College",
    "Gurukul",
    "Bhaktinagar Circle",
    "Kanta Stri Vikash Gruh",
    "S.T. Bus Stand",
    "Trikon Baug",
    "Hospital Chowk",
    "I.P. Mission School",
    "Kothicompound",
    "Junction Railway Station",
    "Popatpara Central Jail",
    "Popatpara",
    "Central Ware House",
    "Bhaktinagar Park"
]

print(list(set(locations)))
