# Define two lists
# list1 = ['131 Slam quarter' , '150 Feet Jamnagar Road Crossing', '50 Feet Road Crossing', '53 Quarter / Popatpara', 'A.G. Society', 'A.G. Staff Quater', 'AV. Jashani T.B. Hospital', 'Aafika Colony', 'Aahir Chowk', 'Aaji 66 KV Station (Vasahat', 'Road Crossing)', 'Aaji G.I.D.C.', 'Aaji Vasahat', 'AajiDam', 'Aajidam Chokdi', 'Aalap Green City', 'Aalap Heritage', 'Aamrapali Fatak', 'Aanand Bunglows', 'Aarti Industrial Area', 'Aarya Land Residency', 'Aaryasamaj', 'Aastha Green City', 'Aastha Sangrila', 'Aayaknagar - Pedak Road', 'Aazad Chowk', 'Ajanta Park / Janak Puri', 'Akashvani Chowk', 'Akshar Complex', 'Akshar Vatika (Mavdi)', 'Aksharnagar', 'Alay Park', 'Alfred HighSchool', 'Alkapuri', 'Ambaji Kadva Plot P.D.M.', 'College', 'Ambedkar Chowk', 'Ambika Township', 'Amin Marg Akshar Marg', 'Crossing', 'Amin Marg Sivik Center', 'Amrut Park Main Road', 'Arpit Eng. College (Hadala Gam)', 'Ashapura Mandir', 'Ashok Garden', 'Astha Residency', 'Astron Chowk', 'Astron Society', 'Atmiya College / Central School', 'Ayodhya Park Chowk', 'B.A. Dangar College', 'BT Savani (Kidni) Hospital', 'Babariya Colony', 'Baby Doll Museum', 'Bahumali Bhavan', 'Bajrangvadi', 'Bajrangvadi Circle', 'Balaji Hanuman', 'Balaji Park/Satellite Park', 'Bapa Sitaram Chowk', 'Bedi', 'Bedi Marketing Yard', 'Bhagavati Para Police Choki', 'Bhagavati Para Sheri No. 9', 'Bhagavatipara (Jay Prakashnagar)', 'Bhagirath Society', 'Bhaktinagar Circle', 'Bhaktinagar Park', 'Bhaktinagar Station', 'Bharad Engineering College', 'Bhomeshvar', 'Bombay Hotel', 'Bramh Samaj', 'Central Jail', 'Central Ware House', 'Champak Nagar - Panino Ghodo', 'Chandranagar Shakmarket', 'Chandreshvadi Chowk', 'Chaudhri Highschool', 'Chitralekha Chowk', 'Christ College', 'Chunarvad Chowk', 'Chunarvad Chowk Ramnath Para (B Division Police Station)', 'Cosmoplex Cinema', 'Crystal Mall', 'Darshan Eng. College', 'Devpara', 'Dharamnagar', 'Dharmendrasihnji College', 'Divanpara
# Police Choki', 'Dr. Aambedkar Chowk', 'Dream City', 'Dudheshvar Mahadev', 'Dudhsagar Road Crossing', 'Everest Park', 'Field Marshal Chowk', 'Fuliya Hanuman Mandir', 'Fulvadi Park', 'G.I.D.C. Gate 1', 'G.I.D.C. Gate 2', 'G.I.D.C. Gate 3',
# 'Gabanshahpir Dargah', 'Gadhiya Nagar', 'Gangotri Park', 'Ganjanand Chowk', 'Gauridal', 'Gautam Nagar', 'Gautam Buddh Nagar', 'Gavridad', 'Gaytridham', 'Ghanshyam Nagar / Nanda Hall', 'Ghanteshvar Gam', 'Ghanteshvar Park', 'Ghanteshvar S.R.P Camp (G- Company Gate)', 'Ghanteshvar S.R.P. Camp', 'Git Gurjari Crossing', 'Gitanagar', 'Gokuldham', 'Gokulnagar Aproch (Nirav Complex)', 'Golden Park', 'Gondal Chokdi', 'Gopalnagar Choro', 'Govani Hostel', 'Goverdhan Chowk', 'Government Engineering College', 'Government Polytechnic', 'Govind Baug', 'Govind Nagar', 'GramUdhyog Mandir Pedak', 'Greenland Chokdi', 'Gujarat Housing Bodak Quarter', 'Gundavadi Police Choki', 'Gurudev Park', 'Gurukul', 'Guruprasad Chowk', 'HN Shukla College', 'Hansraj Nagar', 'Hanuman Madhi', 'Haripar Gam', 'Hemu Gadhvi Hall', 'Hospital Chowk', 'Hudko Police Chokdi', 'I.O.C.', 'I.P. Mission School', 'Indira Circle', 'Indraprasth Society', 'Indubai Mahasatiji Chowk', 'Ishvariya Park', 'J.K.Park (Raiya Gam)', 'Jalaram Chowk (Gayatrinagar Road)', 'Jalaram Chowk (Santkabir Road', 'no Khuno)', 'Jaljit Hall', 'Jangleshwer Crossing/ Bapunagar', 'Jasani School', 'Jashani School Fatak', 'Jay Gopal Chowk', 'Jay Javan Jay Kishan Society', 'Jay Prakashnagar Society', 'Jay Sardar Chowk', 'Jetko Chokdi', 'Jilla Garden Chowk', 'Jilla Panchayat Chowk', 'Jivan Jyot School', 'Jivantika Main Road Crossing', 'Jivraj Hospital', 'Jivraj Park', 'Jograna Chowk', 'Jubilee Baug', 'Jubilee Watson Museum', 'Junction Railway Police Station', 'Junction Railway Station', 'K.K.V. Hall', 'K.S. Diesel Engine (80 feet Road Crossing)', 'Kadvibai School', 'Kankot Kalwad Road', 'Kankot Patiyu', 'Kanta Stri Vikash Gruh', 'Kishanpara Chowk', 'Kothariya', 'Kothariya Chokdi', 'Kothariya Coloni', 'Kothariya Housing', 'Kothariya Solvant', 'Kothicompound', 'Krishna Banglowz-3 (Sadhuvasvani Kunj Road Crossing)', 'Krishna International School', 'Kuvadva Police Choki', 'Labhubhai Engineering college', 'Lakheshvar Society - R.T.O. Office', 'Lakhno Bunglow', 'Lalbahadur Society (Pardi Road)', 'Lashdhara Park', 'Limda Chowk', 'Madhapar Chowk ', 'Madhapar Gam', 'Madhapar Gam Gate', 'Madhurnagar', 'Mahakali Society', 'Mahapuja Dham', 'Mahika Patiyu', 'Mahila College Chowk (L.I.C', 'Office)', 'Makkam Chowk', 'Malaviya Chowk', 'Manhar Pura (150 ft. Ring Road)', 'Manhar Pura / Bedinaka Fire Station', 'Mansarovar Society', 'Mansarovar Society / Om Residency', 'Marketing Yard', 'Maruti Nagar (Sarvodaya Housing Society)', 'Marutinagar 50 Feet Road
# Chowk', 'Marwadi College', 'Mavdi Chowk', 'Mavdi Fire Station', 'Mavdi Gam', 'Mochinagar', 'Mota Mava', 'Mukhyamantri Aavas Yogna Quarter', 'Munjaka Gam', 'Nageshvar Jain Derasar', 'Naloda Nagar', 'Nana Mauva Chowk', 'Nanavati Chowk', 'Narayan Nagar Aproch Road - Govind Nagar', 'Navagam', 'New Rajdeep Society', 'New Subhashnagar', 'Nilkanth Cinema', 'Om Residency', 'Omnagar', 'P and T Colony / Gitanagar', 'P. D. M. College', 'Panchayat Nagar Chowk', 'Panchshil society', 'Panchshill Society Aproch Road (Dalibai Hostel)', 'Pandit Dindayal', 'Parapipaliya Gam (ekta Society)', 'Pardi Gam', 'Pardi Road Crossing', 'Parevadi Chowk', 'Parsananagar', 'Parsananagar (Ayyapa Mandir)', 'Parsananagar Main Road', 'Patel Chowk', 'Patel Vadi', 'Patidar Chowk', 'Pipaliya Hall / Bhakti Hall', 'Police HeadQuarter', 'Popatpara', 'Popatpara Central Jail', 'Popatpara Central Jail', 'Pradyumna Park', 'Prashil Park', 'Pulchhab Chowk', 'Punit Nagar (Jetko 66 k.v.a.)', 'Punitnagar', 'Pushkar dham', 'R.K. University', 'R.M.C East Zone Office', 'R.M.C. Transport Nagar', 'R.T.O. Office', 'Radha Krushna Chowk', 'Radha Mira Industrial Area', 'Raghuvanshi Society', 'Railnagar', 'Railway Colony', 'Raiya Chokdi', 'Raiya Gam', 'Raiya Telephone Exchange', 'Raiyadhar Slam', 'Rajkot Dairy', 'Rajkot Mahanagar Palika - Aavash',
# 'Rajnagar Main Road Crossing', 'Rajshri Auto', 'Ramapir Chokdi', 'Rameshvar Chowk', 'Ramkrushna Aashram', 'Ramnath para Muktidham', 'Ranchhod Aashram', 'Rangoli Park (Lakshmi Dholo)', 'Ranuja Madir', 'Ratanpar (Ramji Mandir)', 'Ratanpar Telephone Exchange', 'Ratanpar gam', 'Refuji Coloni', 'Ruda Office', 'S.B.I. Bank', 'S.T. Bus Stand', 'S.T. Workshop', 'Sadhu Vasvani School', 'Sainik Society', 'Sanidhya Bunglows', 'Sankalp Siddhpark', 'Sanskar City', 'Sant Bhojaram Road
# Crossing', 'Santoshinagar', 'Santoshinagar Railway Crossing', 'Sardar Vallabhbhai Viddhyalay', 'Sarita Vihar', 'Sarvoday Society', 'Satya Prakash School', 'SatyaSai Road Crossing', 'Satyam Park', 'Satyasai Hospital', 'Saurastra University', 'Setelite Chowk - Maruti Nagar Approch Road', 'Shanti Niketan College (Pushkar Dham)', 'Shantiniketan Park', 'Shapar Veraval', 'Shardabaug', 'Shastrinagar', 'Sheth High school', 'Shethnagar', 'Shital Park', 'Shitalamataji Nu Mandir', 'Shiv Shakti Colony', 'Shivdhara Residency', 'Shree City (Munjka gam)', 'Shree Sahjanand Dham', 'Shri Dhrmeshwar Marg Chowk', 'Shyam Hall', 'Shymal City', 'Sinchai Nagar', 'Sorthiya Vadi Circle', 'Special School For Boys', 'Suryamukhi Hanuman Chowk', 'Svashray Society', 'Swaminarayan Chowk', 'Swaminarayan Mandir / Mahila', 'College Chowk', 'Swati Society', 'Taramandal / RaceCource', 'Thebchada - Mahika Patiyu', 'Tramba Gam', 'Transport Nagar', 'Trikon Baug', 'Trishul Chowk', 'Tulshi Baug', 'Udhyog Nagar', 'Uma P.T.C. College', 'Umiya Chowk', 'Unicare Hospital', 'VV.P. Engineering College', 'VadVajdi Gam', 'Vagudad', 'Valkeshvar', 'Vankaner Society', 'Vankaner Society Khuno', 'Vavdi Gam', 'Velnathpara (Sheri No. 17)', 'Velnathpara Saruaat (Shala No. 71 Paase)', 'Vidhyutnagar', 'Vima nu Davakhanu', 'Vimalnagar', 'Vinod Nagar', 'Virda Vajdi Gam', 'Vishvanagar', 'Vora Society', 'Vruksh Mandir', 'Vrundavan Road Crossing', 'Vrundavan Society', 'West Zone Office', 'Wockhardt Hospital', 'Yadunandan Chowk', 'Zulelal Mandir', 'kalipat', 'khokhadadad', 'Ayodhya Park
# Chowk', 'Shital Park', 'Ramdevpir Chowk', 'Nanavati Chowk', 'Raiya Chowk', 'Raiya TelePhone Exchange', 'Indira Circle', 'West Zone Office', 'Nana Mava Chowk', 'Maha Puja Dham Chowk', 'Om Nagar Chowk', 'Mavdi Chowk', 'Umiya Chowk', 'Ambedkar Chowk', 'Goverdhan Chowk', 'Punit Nagar Chowk', 'Gondal Chowk']
locations = [
    "131 Slam quarter",
    "150 Feet Jamnagar Road Crossing",
    "50 Feet Road Crossing",
    "53 Quarter / Popatpara",
    "A.G. Society",
    "A.G. Staff Quater",
    "AV. Jashani T.B. Hospital",
    "Aafika Colony",
    "Aahir Chowk",
    "Aaji 66 KV Station (Vasahat Road Crossing)",
    "Aaji G.I.D.C.",
    "Aaji Vasahat",
    "AajiDam",
    "Aajidam Chokdi",
    "Aalap Green City",
    "Aalap Heritage",
    "Aamrapali Fatak",
    "Aanand Bunglows",
    "Aarti Industrial Area",
    "Aarya Land Residency",
    "Aaryasamaj",
    "Aastha Green City",
    "Aastha Sangrila",
    "Aayaknagar - Pedak Road",
    "Aazad Chowk",
    "Ajanta Park / Janak Puri",
    "Akashvani Chowk",
    "Akshar Complex",
    "Akshar Vatika (Mavdi)",
    "Aksharnagar",
    "Alay Park",
    "Alfred HighSchool",
    "Alkapuri",
    "Ambaji Kadva Plot P.D.M. College",
    "Ambedkar Chowk",
    "Ambika Township",
    "Amin Marg Akshar Marg Crossing",
    "Amin Marg Sivik Center",
    "Amrut Park Main Road",
    "Arpit Eng. College (Hadala Gam)",
    "Ashapura Mandir",
    "Ashok Garden",
    "Astha Residency",
    "Astron Chowk",
    "Astron Society",
    "Atmiya College / Central School",
    "Ayodhya Park Chowk",
    "B.A. Dangar College",
    "BT Savani (Kidni) Hospital",
    "Babariya Colony",
    "Baby Doll Museum",
    "Bahumali Bhavan",
    "Bajrangvadi",
    "Bajrangvadi Circle",
    "Balaji Hanuman",
    "Balaji Park/Satellite Park",
    "Bapa Sitaram Chowk",
    "Bedi",
    "Bedi Marketing Yard",
    "Bhagavati Para Police Choki",
    "Bhagavati Para Sheri No. 9",
    "Bhagavatipara (Jay Prakashnagar)",
    "Bhagirath Society",
    "Bhaktinagar Circle",
    "Bhaktinagar Park",
    "Bhaktinagar Station",
    "Bharad Engineering College",
    "Bhomeshvar",
    "Bombay Hotel",
    "Bramh Samaj",
    "Central Jail",
    "Central Ware House",
    "Champak Nagar - Panino Ghodo",
    "Chandranagar Shakmarket",
    "Chandreshvadi Chowk",
    "Chaudhri Highschool",
    "Chitralekha Chowk",
    "Christ College",
    "Chunarvad Chowk",
    "Chunarvad Chowk Ramnath Para (B Division Police Station)",
    "Cosmoplex Cinema",
    "Crystal Mall",
    "Darshan Eng. College",
    "Devpara",
    "Dharamnagar",
    "Dharmendrasihnji College",
    "Divanpara Police Choki",
    "Dr. Aambedkar Chowk",
    "Dream City",
    "Dudheshvar Mahadev",
    "Dudhsagar Road Crossing",
    "Everest Park",
    "Field Marshal Chowk",
    "Fuliya Hanuman Mandir",
    "Fulvadi Park",
    "G.I.D.C. Gate 1",
    "G.I.D.C. Gate 2",
    "G.I.D.C. Gate 3",
    "Gabanshahpir Dargah",
    "Gadhiya Nagar",
    "Gangotri Park",
    "Ganjanand Chowk",
    "Gauridal",
    "Gautam Nagar",
    "Gautam Buddh Nagar",
    "Gavridad",
    "Gaytridham",
    "Ghanshyam Nagar / Nanda Hall",
    "Ghanteshvar Gam",
    "Ghanteshvar Park",
    "Ghanteshvar S.R.P Camp (G- Company Gate)",
    "Ghanteshvar S.R.P. Camp",
    "Git Gurjari Crossing",
    "Gitanagar",
    "Gokuldham",
    "Gokulnagar Aproch (Nirav Complex)",
    "Golden Park",
    "Gondal Chokdi",
    "Gopalnagar Choro",
    "Govani Hostel",
    "Goverdhan Chowk",
    "Government Engineering College",
    "Government Polytechnic",
    "Govind Baug",
    "Govind Nagar",
    "GramUdhyog Mandir Pedak",
    "Greenland Chokdi",
    "Gujarat Housing Bodak Quarter",
    "Gundavadi Police Choki",
    "Gurudev Park",
    "Gurukul",
    "Guruprasad Chowk",
    "HN Shukla College",
    "Hansraj Nagar",
    "Hanuman Madhi",
    "Haripar Gam",
    "Hemu Gadhvi Hall",
    "Hospital Chowk",
    "Hudko Police Chokdi",
    "I.O.C.",
    "I.P. Mission School",
    "Indira Circle",
    "Indraprasth Society",
    "Indubai Mahasatiji Chowk",
    "Ishvariya Park",
    "J.K.Park (Raiya Gam)",
    "Jalaram Chowk (Gayatrinagar Road)",
    "Jalaram Chowk (Santkabir Road no Khuno)",
    "Jaljit Hall",
    "Jangleshwer Crossing/ Bapunagar",
    "Jasani School",
    "Jashani School Fatak",
    "Jay Gopal Chowk",
    "Jay Javan Jay Kishan Society",
    "Jay Prakashnagar Society",
    "Jay Sardar Chowk",
    "Jetko Chokdi",
    "Jilla Garden Chowk",
    "Jilla Panchayat Chowk",
    "Jivan Jyot School",
    "Jivantika Main Road Crossing",
    "Jivraj Hospital",
    "Jivraj Park",
    "Jograna Chowk",
    "Jubilee Baug",
    "Jubilee Watson Museum",
    "Junction Railway Police Station",
    "Junction Railway Station",
    "K.K.V. Hall",
    "K.S. Diesel Engine (80 feet Road Crossing)",
    "Kadvibai School",
    "Kankot Kalwad Road",
    "Kankot Patiyu",
    "Kanta Stri Vikash Gruh",
    "Kishanpara Chowk",
    "Kothariya",
    "Kothariya Chokdi",
    "Kothariya Coloni",
    "Kothariya Housing",
    "Kothariya Solvant",
    "Kothicompound",
    "Krishna Banglowz-3 (Sadhuvasvani Kunj Road Crossing)",
    "Krishna International School",
    "Kuvadva Police Choki",
    "Labhubhai Engineering college",
    "Lakheshvar Society - R.T.O. Office",
    "Lakhno Bunglow",
    "Lalbahadur Society (Pardi Road)",
    "Lashdhara Park",
    "Limda Chowk",
    "Madhapar Chowk",
    "Madhapar Gam",
    "Madhapar Gam Gate",
    "Madhurnagar",
    "Mahakali Society",
    "Mahapuja Dham",
    "Mahika Patiyu",
    "Mahila College Chowk (L.I.C Office)",
    "Makkam Chowk",
    "Malaviya Chowk",
    "Manhar Pura (150 ft. Ring Road)",
    "Manhar Pura / Bedinaka Fire Station",
    "Mansarovar Society",
    "Mansarovar Society / Om Residency",
    "Marketing Yard",
    "Maruti Nagar (Sarvodaya Housing Society)",
    "Marutinagar 50 Feet Road Chowk",
    "Marwadi College",
    "Mavdi Chowk",
    "Mavdi Fire Station",
    "Mavdi Gam",
    "Mochinagar",
    "Mota Mava",
    "Mukhyamantri Aavas Yogna Quarter",
    "Munjaka Gam",
    "Nageshvar Jain Derasar",
    "Naloda Nagar",
    "Nana Mauva Chowk",
    "Nanavati Chowk",
    "Narayan Nagar Aproch Road - Govind Nagar",
    "Navagam",
    "New Rajdeep Society",
    "New Subhashnagar",
    "Nilkanth Cinema",
    "Om Residency",
    "Omnagar",
    "P and T Colony / Gitanagar",
    "P. D. M. College",
    "Panchayat Nagar Chowk",
    "Panchshil society",
    "Panchshill Society Aproch Road (Dalibai Hostel)",
    "Pandit Dindayal",
    "Parapipaliya Gam (ekta Society)",
    "Pardi Gam",
    "Pardi Road Crossing",
    "Parevadi Chowk",
    "Parsananagar",
    "Parsananagar (Ayyapa Mandir)",
    "Parsananagar Main Road",
    "Patel Chowk",
    "Patel Vadi",
    "Patidar Chowk",
    "Pipaliya Hall / Bhakti Hall",
    "Police HeadQuarter",
    "Popatpara",
    "Popatpara Central Jail",
    "Popatpara Central Jail",
    "Pradyumna Park",
    "Prashil Park",
    "Pulchhab Chowk",
    "Punit Nagar (Jetko 66 k.v.a.)",
    "Punitnagar",
    "Pushkar dham",
    "R.K. University",
    "R.M.C East Zone Office",
    "R.M.C. Transport Nagar",
    "R.T.O. Office",
    "Radha Krushna Chowk",
    "Radha Mira Industrial Area",
    "Raghuvanshi Society",
    "Railnagar",
    "Railway Colony",
    "Raiya Chokdi",
    "Raiya Gam",
    "Raiya Telephone Exchange",
    "Raiyadhar Slam",
    "Rajkot Dairy",
    "Rajkot Mahanagar Palika - Aavash",
    "Rajnagar Main Road Crossing",
    "Rajshri Auto",
    "Ramapir Chokdi",
    "Rameshvar Chowk",
    "Ramkrushna Aashram",
    "Ramnath para Muktidham",
    "Ranchhod Aashram",
    "Rangoli Park (Lakshmi Dholo)",
    "Ranuja Madir",
    "Ratanpar (Ramji Mandir)",
    "Ratanpar Telephone Exchange",
    "Ratanpar gam",
    "Refuji Coloni",
    "Ruda Office",
    "S.B.I. Bank",
    "S.T. Bus Stand",
    "S.T. Workshop",
    "Sadhu Vasvani School",
    "Sainik Society",
    "Sanidhya Bunglows",
    "Sankalp Siddhpark",
    "Sanskar City",
    "Sant Bhojaram Road Crossing",
    "Santoshinagar",
    "Santoshinagar Railway Crossing",
    "Sardar Vallabhbhai Viddhyalay",
    "Sarita Vihar",
    "Sarvoday Society",
    "Satya Prakash School",
    "SatyaSai Road Crossing",
    "Satyam Park",
    "Satyasai Hospital",
    "Saurastra University",
    "Setelite Chowk - Maruti Nagar Approch Road",
    "Shanti Niketan College (Pushkar Dham)",
    "Shantiniketan Park",
    "Shapar Veraval",
    "Shardabaug",
    "Shastrinagar",
    "Sheth High school",
    "Shethnagar",
    "Shital Park",
    "Shitalamataji Nu Mandir",
    "Shiv Shakti Colony",
    "Shivdhara Residency",
    "Shree City (Munjka gam)",
    "Shree Sahjanand Dham",
    "Shri Dhrmeshwar Marg Chowk",
    "Shyam Hall",
    "Shymal City",
    "Sinchai Nagar",
    "Sorthiya Vadi Circle",
    "Special School For Boys",
    "Suryamukhi Hanuman Chowk",
    "Svashray Society",
    "Swaminarayan Chowk",
    "Swaminarayan Mandir / Mahila College Chowk",
    "Swati Society",
    "Taramandal / RaceCource",
    "Thebchada - Mahika Patiyu",
    "Tramba Gam",
    "Transport Nagar",
    "Trikon Baug",
    "Trishul Chowk",
    "Tulshi Baug",
    "Udhyog Nagar",
    "Uma P.T.C. College",
    "Umiya Chowk",
    "Unicare Hospital",
    "VV.P. Engineering College",
    "VadVajdi Gam",
    "Vagudad",
    "Valkeshvar",
    "Vankaner Society",
    "Vankaner Society Khuno",
    "Vavdi Gam",
    "Velnathpara (Sheri No. 17)",
    "Velnathpara Saruaat (Shala No. 71 Paase)",
    "Vidhyutnagar",
    "Vima nu Davakhanu",
    "Vimalnagar",
    "Vinod Nagar",
    "Virda Vajdi Gam",
    "Vishvanagar",
    "Vora Society",
    "Vruksh Mandir",
    "Vrundavan Road Crossing",
    "Vrundavan Society",
    "West Zone Office",
    "Wockhardt Hospital",
    "Yadunandan Chowk",
    "Zulelal Mandir",
    "kalipat",
    "khokhadadad",
    "Ayodhya Park Chowk",
    "Shital Park",
    "Ramdevpir Chowk",
    "Nanavati Chowk",
    "Raiya Chowk",
    "Raiya TelePhone Exchange",
    "Indira Circle",
    "West Zone Office",
    "Nana Mava Chowk",
    "Maha Puja Dham Chowk",
    "Om Nagar Chowk",
    "Mavdi Chowk",
    "Umiya Chowk",
    "Ambedkar Chowk",
    "Goverdhan Chowk",
    "Punit Nagar Chowk",
    "Gondal Chowk"
]


# # Find the missing members in list1 with respect to list2 using list comprehension
# missing_members = [x for x in list1 if x not in list2]

# print("Missing members in list1:", missing_members)

print(len(locations))
