import java.util.*;

public class DJ {
    static class Edge {
        String Destination;
        int Route;
        float distance;

        public Edge(String Destination, int Route, float distance) {
            this.Destination = Destination;
            this.Route = Route;
            this.distance = distance;
        }
    }

    public static String getSrc() {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter Your Source: ");
        return sc.nextLine();
    }

    public static String getTar() {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter Your Target: ");
        return sc.nextLine();
    }

    public static void createGraph(List<Edge>[] graph, Map<String, Integer> stationIndices) {
        stationIndices.put("Udhyog Nagar", 0);
        stationIndices.put("Darshan Eng. College", 1);
        stationIndices.put("Hemu Gadhvi Hall", 2);
        stationIndices.put("S.T. Bus Stand", 3);
        stationIndices.put("Bapa Sitaram Chowk", 4);
        stationIndices.put("Fulvadi Park", 5);
        stationIndices.put("Astron Society", 6);
        stationIndices.put("K.S. Diesel Engine (80 feet Road Crossing)", 7);
        stationIndices.put("Manhar Pura (150 ft. Ring Road)", 8);
        stationIndices.put("Navagam", 9);
        stationIndices.put("Madhapar Gam", 10);
        stationIndices.put("Punit Nagar (Jetko 66 k.v.a.)", 11);
        stationIndices.put("Christ College", 12);
        stationIndices.put("Hudko Police Chokdi", 13);
        stationIndices.put("Swati Society", 14);
        stationIndices.put("Ghanshyam Nagar / Nanda Hall", 15);
        stationIndices.put("Gopalnagar Choro", 16);
        stationIndices.put("Ghanteshvar S.R.P Camp (G- Company Gate)", 17);
        stationIndices.put("Narayan Nagar Aproch Road - Govind Nagar", 18);
        stationIndices.put("Rajnagar Main Road Crossing", 19);
        stationIndices.put("Kankot Patiyu", 20);
        stationIndices.put("Akshar Vatika (Mavdi)", 21);
        stationIndices.put("Vishvanagar", 22);
        stationIndices.put("Greenland Chokdi", 23);
        stationIndices.put("Patidar Chowk", 24);
        stationIndices.put("Aastha Sangrila", 25);
        stationIndices.put("Sankalp Siddhpark", 26);
        stationIndices.put("Punit Nagar Chowk", 27);
        stationIndices.put("Ramkrushna Aashram", 28);
        stationIndices.put("Amin Marg Akshar Marg Crossing", 29);
        stationIndices.put("Panchayat Nagar Chowk", 30);
        stationIndices.put("Chitralekha Chowk", 31);
        stationIndices.put("Jay Sardar Chowk", 32);
        stationIndices.put("K.K.V. Hall", 33);
        stationIndices.put("Sardar Vallabhbhai Viddhyalay", 34);
        stationIndices.put("Indubai Mahasatiji Chowk", 35);
        stationIndices.put("Golden Park", 36);
        stationIndices.put("Indraprasth Society", 37);
        stationIndices.put("R.K. University", 38);
        stationIndices.put("Marwadi College", 39);
        stationIndices.put("Tulshi Baug", 40);
        stationIndices.put("G.I.D.C. Gate 1", 41);
        stationIndices.put("Wockhardt Hospital", 42);
        stationIndices.put("Alkapuri", 43);
        stationIndices.put("Gangotri Park", 44);
        stationIndices.put("Nana Mauva Chowk", 45);
        stationIndices.put("Refuji Coloni", 46);
        stationIndices.put("Bedi Marketing Yard", 47);
        stationIndices.put("G.I.D.C. Gate 2", 48);
        stationIndices.put("Bedi", 49);
        stationIndices.put("G.I.D.C. Gate 3", 50);
        stationIndices.put("Gavridad", 51);
        stationIndices.put("Vankaner Society Khuno", 52);
        stationIndices.put("Bombay Hotel", 53);
        stationIndices.put("Ishvariya Park", 54);
        stationIndices.put("Aalap Green City", 55);
        stationIndices.put("Ranchhod Aashram", 56);
        stationIndices.put("Field Marshal Chowk", 57);
        stationIndices.put("Divanpara Police Choki", 58);
        stationIndices.put("Jangleshwer Crossing/ Bapunagar", 59);
        stationIndices.put("Kanta Stri Vikash Gruh", 60);
        stationIndices.put("A.G. Society", 61);
        stationIndices.put("Aayaknagar - Pedak Road", 62);
        stationIndices.put("Baby Doll Museum", 63);
        stationIndices.put("Jay Gopal Chowk", 64);
        stationIndices.put("Gokulnagar Aproch (Nirav Complex)", 65);
        stationIndices.put("Omnagar", 66);
        stationIndices.put("Sanidhya Bunglows", 67);
        stationIndices.put("Pipaliya Hall / Bhakti Hall", 68);
        stationIndices.put("Santoshinagar", 69);
        stationIndices.put("Madhapar Chowk", 70);
        stationIndices.put("R.M.C East Zone Office", 71);
        stationIndices.put("131 Slam quarter", 72);
        stationIndices.put("Shivdhara Residency", 73);
        stationIndices.put("HN Shukla College", 74);
        stationIndices.put("Jilla Panchayat Chowk", 75);
        stationIndices.put("Vora Society", 76);
        stationIndices.put("Mavdi Fire Station", 77);
        stationIndices.put("Dharamnagar", 78);
        stationIndices.put("Malaviya Chowk", 79);
        stationIndices.put("Maruti Nagar (Sarvodaya Housing Society)", 80);
        stationIndices.put("Champak Nagar - Panino Ghodo", 81);
        stationIndices.put("Sorthiya Vadi Circle", 82);
        stationIndices.put("Patel Chowk", 83);
        stationIndices.put("Jetko Chokdi", 84);
        stationIndices.put("S.B.I. Bank", 85);
        stationIndices.put("Aajidam Chokdi", 86);
        stationIndices.put("Government Engineering College", 87);
        stationIndices.put("Mansarovar Society / Om Residency", 88);
        stationIndices.put("Rajkot Mahanagar Palika - Aavash", 89);
        stationIndices.put("Mahila College Chowk (L.I.C Office)", 90);
        stationIndices.put("Yadunandan Chowk", 91);
        stationIndices.put("Unicare Hospital", 92);
        stationIndices.put("Bhagirath Society", 93);
        stationIndices.put("Govani Hostel", 94);
        stationIndices.put("Balaji Hanuman", 95);
        stationIndices.put("Junction Railway Station", 96);
        stationIndices.put("Zulelal Mandir", 97);
        stationIndices.put("Aaryasamaj", 98);
        stationIndices.put("Krishna Banglowz-3 (Sadhuvasvani Kunj Road Crossing)", 99);
        stationIndices.put("Lakhno Bunglow", 100);
        stationIndices.put("Parsananagar Main Road", 101);
        stationIndices.put("Jivantika Main Road Crossing", 102);
        stationIndices.put("Radha Krushna Chowk", 103);
        stationIndices.put("Bajrangvadi Circle", 104);
        stationIndices.put("New Subhashnagar", 105);
        stationIndices.put("Mukhyamantri Aavas Yogna Quarter", 106);
        stationIndices.put("Hospital Chowk", 107);
        stationIndices.put("Shyam Hall", 108);
        stationIndices.put("Rajkot Dairy", 109);
        stationIndices.put("Madhapar Gam Gate", 110);
        stationIndices.put("Vavdi Gam", 111);
        stationIndices.put("khokhadadad", 112);
        stationIndices.put("Kothariya Chokdi", 113);
        stationIndices.put("Saurastra University", 114);
        stationIndices.put("Tramba Gam", 115);
        stationIndices.put("Nanavati Chowk", 116);
        stationIndices.put("Thebchada - Mahika Patiyu", 117);
        stationIndices.put("VV.P. Engineering College", 118);
        stationIndices.put("Raiya Gam", 119);
        stationIndices.put("Gadhiya Nagar", 120);
        stationIndices.put("Satya Prakash School", 121);
        stationIndices.put("Shantiniketan Park", 122);
        stationIndices.put("Bhaktinagar Circle", 123);
        stationIndices.put("Hansraj Nagar", 124);
        stationIndices.put("GramUdhyog Mandir Pedak", 125);
        stationIndices.put("Sainik Society", 126);
        stationIndices.put("Sarvoday Society", 127);
        stationIndices.put("Vimalnagar", 128);
        stationIndices.put("Alfred HighSchool", 129);
        stationIndices.put("Aalap Heritage", 130);
        stationIndices.put("Aafika Colony", 131);
        stationIndices.put("Vrundavan Road Crossing", 132);
        stationIndices.put("Shanti Niketan College (Pushkar Dham)", 133);
        stationIndices.put("Kadvibai School", 134);
        stationIndices.put("Shiv Shakti Colony", 135);
        stationIndices.put("Gaytridham", 136);
        stationIndices.put("New Rajdeep Society", 137);
        stationIndices.put("Gondal Chokdi", 138);
        stationIndices.put("Kothariya Housing", 139);
        stationIndices.put("Shethnagar", 140);
        stationIndices.put("SatyaSai Road Crossing", 141);
        stationIndices.put("Transport Nagar", 142);
        stationIndices.put("Jalaram Chowk (Santkabir Road no Khuno)", 143);
        stationIndices.put("Munjaka Gam", 144);
        stationIndices.put("Crystal Mall", 145);
        stationIndices.put("R.T.O. Office", 146);
        stationIndices.put("S.T. Workshop", 147);
        stationIndices.put("Parevadi Chowk", 148);
        stationIndices.put("Gondal Chowk", 149);
        stationIndices.put("Aaji Vasahat", 150);
        stationIndices.put("Labhubhai Engineering college", 151);
        stationIndices.put("Suryamukhi Hanuman Chowk", 152);
        stationIndices.put("Ramdevpir Chowk", 153);
        stationIndices.put("A.G. Staff Quater", 154);
        stationIndices.put("Jasani School", 155);
        stationIndices.put("Svashray Society", 156);
        stationIndices.put("Chandreshvadi Chowk", 157);
        stationIndices.put("Makkam Chowk", 158);
        stationIndices.put("Amrut Park Main Road", 159);
        stationIndices.put("Vidhyutnagar", 160);
        stationIndices.put("Rameshvar Chowk", 161);
        stationIndices.put("Trikon Baug", 162);
        stationIndices.put("Lakheshvar Society - R.T.O. Office", 163);
        stationIndices.put("Gauridal", 164);
        stationIndices.put("Gurudev Park", 165);
        stationIndices.put("Junction Railway Police Station", 166);
        stationIndices.put("Popatpara", 167);
        stationIndices.put("Aanand Bunglows", 168);
        stationIndices.put("Shitalamataji Nu Mandir", 169);
        stationIndices.put("Gitanagar", 170);
        stationIndices.put("Vankaner Society", 171);
        stationIndices.put("Vima nu Davakhanu", 172);
        stationIndices.put("Govind Baug", 173);
        stationIndices.put("Aamrapali Fatak", 174);
        stationIndices.put("Railnagar", 175);
        stationIndices.put("Pardi Road Crossing", 176);
        stationIndices.put("Sadhu Vasvani School", 177);
        stationIndices.put("Guruprasad Chowk", 178);
        stationIndices.put("Git Gurjari Crossing", 179);
        stationIndices.put("Govind Nagar", 180);
        stationIndices.put("Nana Mava Chowk", 181);
        stationIndices.put("150 Feet Jamnagar Road Crossing", 182);
        stationIndices.put("Naloda Nagar", 183);
        stationIndices.put("Sinchai Nagar", 184);
        stationIndices.put("Swaminarayan Chowk", 185);
        stationIndices.put("Chunarvad Chowk Ramnath Para (B Division Police Station)", 186);
        stationIndices.put("P. D. M. College", 187);
        stationIndices.put("Pardi Gam", 188);
        stationIndices.put("Bhaktinagar Station", 189);
        stationIndices.put("Jivraj Park", 190);
        stationIndices.put("Nilkanth Cinema", 191);
        stationIndices.put("53 Quarter / Popatpara", 192);
        stationIndices.put("Swaminarayan Mandir / Mahila College Chowk", 193);
        stationIndices.put("Gabanshahpir Dargah", 194);
        stationIndices.put("I.P. Mission School", 195);
        stationIndices.put("Ramnath para Muktidham", 196);
        stationIndices.put("Gautam Buddh Nagar", 197);
        stationIndices.put("Popatpara Central Jail", 198);
        stationIndices.put("Pushkar dham", 199);
        stationIndices.put("Police HeadQuarter", 200);
        stationIndices.put("Sant Bhojaram Road Crossing", 201);
        stationIndices.put("Astron Chowk", 202);
        stationIndices.put("Chunarvad Chowk", 203);
        stationIndices.put("Shree Sahjanand Dham", 204);
        stationIndices.put("Trishul Chowk", 205);
        stationIndices.put("Bramh Samaj", 206);
        stationIndices.put("Vrundavan Society", 207);
        stationIndices.put("Ghanteshvar S.R.P. Camp", 208);
        stationIndices.put("Shree City (Munjka gam)", 209);
        stationIndices.put("Vinod Nagar", 210);
        stationIndices.put("Ashapura Mandir", 211);
        stationIndices.put("Goverdhan Chowk", 212);
        stationIndices.put("Umiya Chowk", 213);
        stationIndices.put("Akshar Complex", 214);
        stationIndices.put("Government Polytechnic", 215);
        stationIndices.put("Jay Prakashnagar Society", 216);
        stationIndices.put("Babariya Colony", 217);
        stationIndices.put("Kothicompound", 218);
        stationIndices.put("Satyam Park", 219);
        stationIndices.put("Ratanpar Telephone Exchange", 220);
        stationIndices.put("Taramandal / RaceCource", 221);
        stationIndices.put("Ambika Township", 222);
        stationIndices.put("Jaljit Hall", 223);
        stationIndices.put("Mochinagar", 224);
        stationIndices.put("Fuliya Hanuman Mandir", 225);
        stationIndices.put("Hanuman Madhi", 226);
        stationIndices.put("Aaji 66 KV Station (Vasahat Road Crossing)", 227);
        stationIndices.put("Vagudad", 228);
        stationIndices.put("Gurukul", 229);
        stationIndices.put("Raghuvanshi Society", 230);
        stationIndices.put("Astha Residency", 231);
        stationIndices.put("Om Residency", 232);
        stationIndices.put("Haripar Gam", 233);
        stationIndices.put("Marketing Yard", 234);
        stationIndices.put("Kothariya Coloni", 235);
        stationIndices.put("Manhar Pura / Bedinaka Fire Station", 236);
        stationIndices.put("Aaji G.I.D.C.", 237);
        stationIndices.put("Chandranagar Shakmarket", 238);
        stationIndices.put("Ghanteshvar Park", 239);
        stationIndices.put("Limda Chowk", 240);
        stationIndices.put("Madhurnagar", 241);
        stationIndices.put("50 Feet Road Crossing", 242);
        stationIndices.put("Jalaram Chowk (Gayatrinagar Road)", 243);
        stationIndices.put("Dudhsagar Road Crossing", 244);
        stationIndices.put("Aksharnagar", 245);
        stationIndices.put("Vruksh Mandir", 246);
        stationIndices.put("Sarita Vihar", 247);
        stationIndices.put("Rajshri Auto", 248);
        stationIndices.put("Ramapir Chokdi", 249);
        stationIndices.put("Sanskar City", 250);
        stationIndices.put("Kankot Kalwad Road", 251);
        stationIndices.put("Aarti Industrial Area", 252);
        stationIndices.put("Mahika Patiyu", 253);
        stationIndices.put("Ambaji Kadva Plot P.D.M. College", 254);
        stationIndices.put("R.M.C. Transport Nagar", 255);
        stationIndices.put("Ratanpar (Ramji Mandir)", 256);
        stationIndices.put("Central Jail", 257);
        stationIndices.put("Dr. Aambedkar Chowk", 258);
        stationIndices.put("Dudheshvar Mahadev", 259);
        stationIndices.put("Dream City", 260);
        stationIndices.put("Prashil Park", 261);
        stationIndices.put("VadVajdi Gam", 262);
        stationIndices.put("Pulchhab Chowk", 263);
        stationIndices.put("Aahir Chowk", 264);
        stationIndices.put("Mansarovar Society", 265);
        stationIndices.put("Arpit Eng. College (Hadala Gam)", 266);
        stationIndices.put("Devpara", 267);
        stationIndices.put("Ranuja Madir", 268);
        stationIndices.put("Jay Javan Jay Kishan Society", 269);
        stationIndices.put("Punitnagar", 270);
        stationIndices.put("Kishanpara Chowk", 271);
        stationIndices.put("Shymal City", 272);
        stationIndices.put("Jilla Garden Chowk", 273);
        stationIndices.put("Central Ware House", 274);
        stationIndices.put("Mahapuja Dham", 275);
        stationIndices.put("Shardabaug", 276);
        stationIndices.put("Pradyaumna Park", 277);
        stationIndices.put("Satyasai Hospital", 278);
        stationIndices.put("Kothariya", 279);
        stationIndices.put("Railway Colony", 280);
        stationIndices.put("Ayodhya Park Chowk", 281);
        stationIndices.put("Patel Vadi", 282);
        stationIndices.put("Ambedkar Chowk", 283);
        stationIndices.put("Ashok Garden", 284);
        stationIndices.put("Jivraj Hospital", 285);
        stationIndices.put("Kothariya Solvant", 286);
        stationIndices.put("Bhomeshvar", 287);
        stationIndices.put("Gokuldham", 288);
        stationIndices.put("Jubilee Watson Museum", 289);
        stationIndices.put("Mahakali Society", 290);
        stationIndices.put("Everest Park", 291);
        stationIndices.put("Lashdhara Park", 292);
        stationIndices.put("Velnathpara Saruaat (Shala No. 71 Paase)", 293);
        stationIndices.put("Shapar Veraval", 294);
        stationIndices.put("Jograna Chowk", 295);
        stationIndices.put("Sheth High school", 296);
        stationIndices.put("Parsananagar (Ayyapa Mandir)", 297);
        stationIndices.put("Bahumali Bhavan", 298);
        stationIndices.put("Raiya Chowk", 299);
        stationIndices.put("Bhagavati Para Sheri No. 9", 300);
        stationIndices.put("Aaji Dam", 301);
        stationIndices.put("Atmiya College / Central School", 302);
        stationIndices.put("Virda Vajdi Gam", 303);
        stationIndices.put("Panchshil society", 304);
        stationIndices.put("Kalipat", 305);
        stationIndices.put("Bharad Engineering College", 306);
        stationIndices.put("Chaudhri Highschool", 307);
        stationIndices.put("Aastha Green City", 308);
        stationIndices.put("Parsananagar", 309);
        stationIndices.put("Uma P.T.C. College", 310);
        stationIndices.put("Ruda Office", 311);
        stationIndices.put("Kuvadva Police Choki", 312);
        stationIndices.put("Raiya TelePhone Exchange", 313);
        stationIndices.put("Special School For Boys", 314);
        stationIndices.put("Gundavadi Police Choki", 315);
        stationIndices.put("Gautam Nagar", 316);
        stationIndices.put("Raiya Chokdi", 317);
        stationIndices.put("Jubilee Baug", 318);
        stationIndices.put("Panchshill Society Approach Road (Dalibai Hostel)", 319);
        stationIndices.put("Bhagavatipara (Jay Prakashnagar)", 320);
        stationIndices.put("Aarya Land Residency", 321);
        stationIndices.put("Alay Park", 322);
        stationIndices.put("Ratanpar gam", 323);
        stationIndices.put("Bajrangvadi", 324);
        stationIndices.put("Indira Circle", 325);
        stationIndices.put("Amin Marg Sivik Center", 326);
        stationIndices.put("Jashani School Fatak", 327);
        stationIndices.put("Ganjanand Chowk", 328);
        stationIndices.put("Krishna International School", 329);
        stationIndices.put("Marutinagar 50 Feet Road Chowk", 330);
        stationIndices.put("Radha Mira Industrial Area", 331);
        stationIndices.put("Valkeshvar", 332);
        stationIndices.put("J.K.Park (Raiya Gam)", 333);
        stationIndices.put("Mota Mava", 334);
        stationIndices.put("Raiya Telephone Exchange", 335);
        stationIndices.put("Setelite Chowk - Maruti Nagar Approach Road", 336);
        stationIndices.put("Cosmoplex Cinema", 337);
        stationIndices.put("Mavdi Chowk", 338);
        stationIndices.put("Maha Puja Dham Chowk", 339);
        stationIndices.put("Om Nagar Chowk", 340);
        stationIndices.put("Bhaktinagar Park", 341);
        stationIndices.put("Jivan Jyot School", 342);
        stationIndices.put("Ajanta Park / Janak Puri", 343);
        stationIndices.put("AV. Jashani T.B. Hospital", 344);
        stationIndices.put("Mavdi Gam", 345);
        stationIndices.put("Santoshinagar Railway Crossing", 346);
        stationIndices.put("Balaji Park/Satellite Park", 347);
        stationIndices.put("Shri Dhrmeshwar Marg Chowk", 348);
        stationIndices.put("Dharmendrasihnji College", 349);
        stationIndices.put("P and T Colony / Gitanagar", 350);
        stationIndices.put("Aazad Chowk", 351);
        stationIndices.put("West Zone Office", 352);
        stationIndices.put("Akashvani Chowk", 353);
        stationIndices.put("Shastrinagar", 354);
        stationIndices.put("Velnathpara (Sheri No. 17)", 355);
        stationIndices.put("Parapipaliya Gam (Ekta Society)", 356);
        stationIndices.put("Lalbahadur Society (Pardi Road)", 357);
        stationIndices.put("Raiyadhar Slam", 358);
        stationIndices.put("Gujarat Housing Bodak Quarter", 359);
        stationIndices.put("I.O.C.", 360);
        stationIndices.put("BT Savani (Kidni) Hospital", 361);
        stationIndices.put("Nageshvar Jain Derasar", 362);
        stationIndices.put("Bhagavati Para Police Choki", 363);
        stationIndices.put("B.A. Dangar College", 364);
        stationIndices.put("Shital Park", 365);
        stationIndices.put("Rangoli Park (Lakshmi Dholo)", 366);
        stationIndices.put("Ghanteshvar Gam", 367);
        stationIndices.put("Pandit Dindayal", 368);
        stationIndices.put("Swaminarayan Mandir / Mahila", 369);
        stationIndices.put("Balaji Park / Satellite Park", 370);
        stationIndices.put("Manhar Pura/Bedinaka Fire Station", 371);
        stationIndices.put("Atmiya College/Central School", 372);
        stationIndices.put("Mukhyamantri Aavas Yogna Quater", 373);
        stationIndices.put("W.P. Engineering College", 374);
        stationIndices.put("Vagudad VadVajdi Gam", 375);
        stationIndices.put("Thebchada Mahika Patiyu", 376);
        
        graph[70].add(new Edge("Ayodhya Park Chowk", 0, 0.6f));
        graph[281].add(new Edge("Shital Park", 0, 0.65f));
        graph[365].add(new Edge("Ramdevpir Chowk", 0, 0.9f));
        graph[153].add(new Edge("Nanavati Chowk", 0, 0.75f));
        graph[116].add(new Edge("Raiya Chowk", 0, 0.55f));
        graph[299].add(new Edge("Raiya TelePhone Exchange", 0, 1.2f));
        graph[313].add(new Edge("Indira Circle", 0, 0.8f));
        graph[325].add(new Edge("West Zone Office", 0, 1.4f));
        graph[352].add(new Edge("Nana Mava Chowk", 0, 0.65f));
        graph[181].add(new Edge("Maha Puja Dham Chowk", 0, 0.7f));
        graph[339].add(new Edge("Om Nagar Chowk", 0, 0.5f));
        graph[340].add(new Edge("Mavdi Chowk", 0, 0.55f));
        graph[338].add(new Edge("Umiya Chowk", 0, 0.7f));
        graph[213].add(new Edge("Ambedkar Chowk", 0, 0.7f));
        graph[283].add(new Edge("Goverdhan Chowk", 0, 0.5f));
        graph[212].add(new Edge("Punit Nagar Chowk", 0, 0.6f));
        graph[27].add(new Edge("Gondal Chowk", 0, 0.75f));

        graph[281].add(new Edge("Madhapar Chowk", 0 ,0.6f));
        graph[365].add(new Edge("Ayodhya Park Chowk",0, 0.65f));
        graph[153].add(new Edge("Shital Park",0, 0.9f));
        graph[116].add(new Edge("Ramdevpir Chowk",0, 0.75f));
        graph[299].add(new Edge("Nanavati Chowk",0, 0.55f));
        graph[313].add(new Edge("Raiya Chowk",0, 1.2f));
        graph[325].add(new Edge("Raiya TelePhone Exchange",0, 0.8f));
        graph[352].add(new Edge("Indira Circle", 0,1.4f));
        graph[181].add(new Edge("West Zone Office",0, 0.65f));
        graph[339].add(new Edge("Maha Puja Dham Chowk", 0,0.7f));
        graph[340].add(new Edge("Om Nagar Chowk",0, 0.5f));
        graph[338].add(new Edge("Mavdi Chowk",0, 0.55f));
        graph[213].add(new Edge("Umiya Chowk",0, 0.7f));
        graph[283].add(new Edge("Ambedkar Chowk", 0,0.7f));
        graph[212].add(new Edge("Goverdhan Chowk", 0,0.5f));
        graph[27].add(new Edge("Punit Nagar Chowk", 0,0.6f));
        graph[149].add(new Edge("Gondal Chowk",0, 0.75f));
        
        // Route - 1 
        
        graph[114].add(new Edge("BT Savani (Kidni) Hospital", 0, 1.4f));
        graph[361].add(new Edge("Akashvani Chowk", 0, 0.75f));
        graph[353].add(new Edge("Panchayat Nagar Chowk", 0, 0.8f));
        graph[30].add(new Edge("Indira Circle", 0, 0.65f));
        graph[325].add(new Edge("Indubai Mahasatiji Chowk", 0, 0.85f));
        graph[35].add(new Edge("Swaminarayan Mandir / Mahila", 0, 0.8f));
        graph[369].add(new Edge("Astron Chowk", 0, 0.85f));
        graph[202].add(new Edge("Hemu Gadhvi Hall", 0, 1.1f));
        graph[2].add(new Edge("Ramkrushna Aashram", 0, 0.75f));
        graph[28].add(new Edge("Malaviya Chowk", 0, 0.75f));
        graph[79].add(new Edge("Trikon Baug", 0, 0.6f));

        graph[162].add(new Edge("Saurastra University", 1, 1.4f));
        graph[361].add(new Edge("BT Savani (Kidni) Hospital", 1, 0.75f));
        graph[114].add(new Edge("Akashvani Chowk", 1, 0.8f));
        graph[325].add(new Edge("Panchayat Nagar Chowk", 1, 0.65f));
        graph[35].add(new Edge("Indira Circle", 1, 0.85f));
        graph[369].add(new Edge("Indubai Mahasatiji Chowk", 1, 0.8f));
        graph[202].add(new Edge("Swaminarayan Mandir / Mahila", 1, 0.85f));
        graph[2].add(new Edge("Hemu Gadhvi Hall", 1, 1.1f));
        graph[28].add(new Edge("Ramkrushna Aashram", 1, 0.75f));
        graph[79].add(new Edge("Malaviya Chowk", 1, 0.75f));
        graph[162].add(new Edge("Trikon Baug", 1, 0.6f));
        
        // Route - 2
        
        graph[74].add(new Edge("Pradyumna Park", 2, 8.7f));
        graph[277].add(new Edge("Marketing Yard", 2, 5.3f));
        graph[234].add(new Edge("Bhagirath Society", 2, 1.3f));
        graph[93].add(new Edge("Lakheshvar Society - R.T.O. Office", 2, 0.3f));
        graph[163].add(new Edge("GramUdhyog Mandir Pedak", 2, 0.9f));
        graph[125].add(new Edge("Setelite Chowk - Maruti Nagar Approch Road", 2, 1.1f));
        graph[336].add(new Edge("Aayaknagar - Pedak Road", 2, 5.4f));
        graph[62].add(new Edge("Narayan Nagar Aproch Road - Govind Nagar", 2, 4.7f));
        graph[18].add(new Edge("Champak Nagar - Panino Ghodo", 2, 0.2f));
        graph[81].add(new Edge("Patel Vadi", 2, 9.1f));
        graph[282].add(new Edge("Parevadi Chowk", 2, 1f));
        graph[148].add(new Edge("Hospital Chowk", 2, 2.6f));
        graph[107].add(new Edge("Trikon Baug", 2, 2.8f));
        graph[162].add(new Edge("Malaviya Chowk", 2, 0.65f));
        graph[79].add(new Edge("Ramkrushna Aashram", 2, 0.8f));
        graph[28].add(new Edge("Dharmendrasihnji College", 2, 0.28f));
        graph[349].add(new Edge("Jilla Panchayat Chowk", 2, 1.6f));
        graph[75].add(new Edge("Kishanpara Chowk", 2, 2.2f));
        graph[271].add(new Edge("Swaminarayan Mandir / Mahila", 2, 0.75f));
        graph[369].add(new Edge("Indubai Mahasatiji Chowk", 2, 1.8f));
        graph[35].add(new Edge("Indira Circle", 2, 2.8f));
        graph[325].add(new Edge("Panchayat Nagar Chowk", 2, 0.9f));
        graph[30].add(new Edge("Sadhu Vasvani School", 2, 5.9f));
        graph[177].add(new Edge("Ajanta Park / Janak Puri", 2, 0.9f));
        graph[343].add(new Edge("Balaji Park / Satellite Park", 2, 0.92f));
        graph[370].add(new Edge("Aalap Green City", 2, 2.2f));
        graph[55].add(new Edge("Raiya Gam", 2, 3.4f));
        
        graph[277].add(new Edge("HN Shukla College", 2, 8.7f));
        graph[234].add(new Edge("Pradyumna Park", 2, 5.3f));
        graph[93].add(new Edge("Marketing Yard", 2, 1.3f));
        graph[163].add(new Edge("Bhagirath Society", 2, 0.3f));
        graph[125].add(new Edge("Lakheshvar Society - R.T.O. Office", 2, 0.9f));
        graph[336].add(new Edge("GramUdhyog Mandir Pedak", 2, 1.1f));
        graph[62].add(new Edge("Setelite Chowk - Maruti Nagar Approach Road", 2, 5.4f));
        graph[18].add(new Edge("Aayaknagar - Pedak Road", 2, 4.7f));
        graph[81].add(new Edge("Narayan Nagar Approach Road - Govind Nagar", 2, 0.2f));
        graph[282].add(new Edge("Champak Nagar - Panino Ghodo", 2, 9.1f));
        graph[148].add(new Edge("Patel Vadi", 2, 1f));
        graph[107].add(new Edge("Parevadi Chowk", 2, 2.6f));
        graph[162].add(new Edge("Hospital Chowk", 2, 2.8f));
        graph[79].add(new Edge("Trikon Baug", 2, 0.65f));
        graph[28].add(new Edge("Malaviya Chowk", 2, 0.8f));
        graph[349].add(new Edge("Ramkrushna Aashram", 2, 0.28f));
        graph[75].add(new Edge("Dharmendrasihnji College", 2, 1.6f));
        graph[271].add(new Edge("Jilla Panchayat Chowk", 2, 2.2f));
        graph[369].add(new Edge("Kishanpara Chowk", 2, 0.75f));
        graph[35].add(new Edge("Swaminarayan Mandir / Mahila", 2, 1.8f));
        graph[325].add(new Edge("Indubai Mahasatiji Chowk", 2, 2.8f));
        graph[30].add(new Edge("Panchayat Nagar Chowk", 2, 0.9f));
        graph[177].add(new Edge("Sadhu Vasvani School", 2, 5.9f));
        graph[343].add(new Edge("Ajanta Park / Janak Puri", 2, 0.9f));
        graph[370].add(new Edge("Balaji Park / Satellite Park", 2, 0.92f));
        graph[55].add(new Edge("Aalap Green City", 2, 2.2f));
        graph[119].add(new Edge("Raiya Gam", 2, 3.4f));
        
        // Route - 3
        
        graph[190].add(new Edge("Aarya Land Residency", 3, 0.5f));
        graph[321].add(new Edge("Jetko Chokdi", 3, 1.5f));
        graph[84].add(new Edge("Dream City", 3, 1.5f));
        graph[260].add(new Edge("Mavdi Gam", 3, 1.2f));
        graph[345].add(new Edge("Mavdi Chowk", 3, 1.2f));
        graph[338].add(new Edge("Fuliya Hanuman Mandir", 3, 0.8f));
        graph[225].add(new Edge("Mavdi Fire Station", 3, 0.25f));
        graph[77].add(new Edge("Aanand Bunglows", 3, 0.45f));
        graph[168].add(new Edge("Swaminarayan Chowk", 3, 0.6f));
        graph[185].add(new Edge("P. D. M. College", 3, 0.95f));
        graph[187].add(new Edge("Gurukul", 3, 1f));
        graph[229].add(new Edge("Bhaktinagar Circle", 3, 0.75f));
        graph[123].add(new Edge("Kanta Stri Vikash Gruh", 3, 0.7f));
        graph[60].add(new Edge("S.T. Bus Stand", 3, 0.9f));
        graph[3].add(new Edge("Trikon Baug", 3, 0.8f));
        graph[162].add(new Edge("Hospital Chowk", 3, 1.2f));
        graph[107].add(new Edge("I.P. Mission School", 3, 0.6f));
        graph[195].add(new Edge("Kothicompound", 3, 1f));
        graph[218].add(new Edge("Junction Railway Station", 3, 0.6f));
        graph[96].add(new Edge("Popatpara Central Jail", 3, 1.9f));
        graph[198].add(new Edge("Popatpara", 3, 0.95f));
        graph[167].add(new Edge("Central Ware House", 3, 0.6f));
        graph[274].add(new Edge("Bhaktinagar Park", 3, 6.3f));

        graph[321].add(new Edge("Jivraj Park", 3, 0.5f));
        graph[84].add(new Edge("Aarya Land Residency", 3, 1.5f));
        graph[260].add(new Edge("Jetko Chokdi", 3, 1.5f));
        graph[345].add(new Edge("Dream City", 3, 1.2f));
        graph[338].add(new Edge("Mavdi Gam", 3, 1.2f));
        graph[225].add(new Edge("Mavdi Chowk", 3, 0.8f));
        graph[77].add(new Edge("Fuliya Hanuman Mandir", 3, 0.25f));
        graph[168].add(new Edge("Mavdi Fire Station", 3, 0.45f));
        graph[185].add(new Edge("Aanand Bunglows", 3, 0.6f));
        graph[187].add(new Edge("Swaminarayan Chowk", 3, 0.95f));
        graph[229].add(new Edge("P. D. M. College", 3, 1f));
        graph[123].add(new Edge("Gurukul", 3, 0.75f));
        graph[60].add(new Edge("Bhaktinagar Circle", 3, 0.7f));
        graph[3].add(new Edge("Kanta Stri Vikash Gruh", 3, 0.9f));
        graph[162].add(new Edge("S.T. Bus Stand", 3, 0.8f));
        graph[107].add(new Edge("Trikon Baug", 3, 1.2f));
        graph[195].add(new Edge("Hospital Chowk", 3, 0.6f));
        graph[218].add(new Edge("I.P. Mission School", 3, 1f));
        graph[96].add(new Edge("Kothicompound", 3, 0.6f));
        graph[198].add(new Edge("Junction Railway Station", 3, 1.9f));
        graph[167].add(new Edge("Popatpara Central Jail", 3, 0.95f));
        graph[274].add(new Edge("Popatpara", 3, 0.6f));
        graph[341].add(new Edge("Central Ware House", 3, 6.3f));

        // Route - 4
        graph[301].add(new Edge("Government Polytechnic", 4, 0.19f));
        graph[215].add(new Edge("Field Marshal Chowk", 4, 1.20f));
        graph[57].add(new Edge("Sarvoday Society", 4, 0.95f));
        graph[127].add(new Edge("Udhyog Nagar", 4, 2.80f));
        graph[0].add(new Edge("Chunarvad Chowk", 4, 3.60f));
        graph[203].add(new Edge("R.M.C East Zone Office", 4, 0.50f));
        graph[71].add(new Edge("Manhar Pura/Bedinaka Fire Station", 4, 5.10f));
        graph[371].add(new Edge("Jalaram Chowk (Santkabir Road no Khuno)", 4, 5.80f));
        graph[143].add(new Edge("Patel Vadi", 4, 8.50f));
        graph[282].add(new Edge("Parevadi Chowk", 4, 9.10f));
        graph[148].add(new Edge("I.P. Mission School", 4, 1.20f));
        graph[195].add(new Edge("Hospital Chowk", 4, 1.30f));
        graph[107].add(new Edge("Jubilee Baug", 4, 0.28f));
        graph[318].add(new Edge("Trikon Baug", 4, 0.55f));
        graph[162].add(new Edge("Malaviya Chowk", 4, 0.75f));
        graph[79].add(new Edge("Ramkrushna Aashram", 4, 0.60f));
        graph[28].add(new Edge("Hemu Gadhvi Hall", 4, 0.85f));
        graph[2].add(new Edge("Astron Chowk", 4, 0.35f));
        graph[202].add(new Edge("Swaminarayan Mandir / Mahila College Chowk", 4, 0.90f));
        graph[193].add(new Edge("Indubai Mahasatiji Chowk", 4, 1.70f));
        graph[35].add(new Edge("K.K.V. Hall", 4, 1.00f));
        graph[33].add(new Edge("Atmiya College/Central School", 4, 0.75f));
        graph[372].add(new Edge("Crystal Mall", 4, 0.35f));
        graph[145].add(new Edge("Vrundavan Society", 4, 8.80f));
        graph[207].add(new Edge("A.G. Society", 4, 9.90f));
        graph[61].add(new Edge("Everest Park", 4, 0.80f));
        graph[291].add(new Edge("Mota Mava", 4, 2.60f));
        graph[334].add(new Edge("Cosmoplex Cinema", 4, 3.30f));
        graph[337].add(new Edge("Kankot Kalwad Road", 4, 0.70f));
        graph[251].add(new Edge("Vruksh Mandir", 4, 0.70f));
        graph[246].add(new Edge("Uma P.T.C. College", 4, 0.90f));
        graph[310].add(new Edge("Mukhyamantri Aavas Yogna Quater", 4, 1.40f));
        graph[373].add(new Edge("Haripar Gam", 4, 3.30f));
        graph[233].add(new Edge("W.P. Engineering College", 4, 1.70f));
        graph[374].add(new Edge("Virda Vajdi Gam", 4, 1.10f));
        graph[303].add(new Edge("Vagudad VadVajdi Gam", 4, 6.00f));
        graph[375].add(new Edge("G.I.D.C. Gate 1", 4, 5.50f));
        graph[41].add(new Edge("G.I.D.C. Gate 2", 4, 0.15f));
        graph[48].add(new Edge("G.I.D.C. Gate 3", 4, 0.70f));

        graph[215].add(new Edge("Government Polytechnic", 4, 0.19f));
        graph[57].add(new Edge("Field Marshal Chowk", 4, 1.20f));
        graph[127].add(new Edge("Sarvoday Society", 4, 0.95f));
        graph[0].add(new Edge("Udhyog Nagar", 4, 2.80f));
        graph[203].add(new Edge("Chunarvad Chowk", 4, 3.60f));
        graph[71].add(new Edge("R.M.C East Zone Office", 4, 0.50f));
        graph[371].add(new Edge("Manhar Pura/Bedinaka Fire Station", 4, 5.10f));
        graph[143].add(new Edge("Jalaram Chowk (Santkabir Road no Khuno)", 4, 5.80f));
        graph[282].add(new Edge("Patel Vadi", 4, 8.50f));
        graph[148].add(new Edge("Parevadi Chowk", 4, 9.10f));
        graph[195].add(new Edge("I.P. Mission School", 4, 1.20f));
        graph[107].add(new Edge("Hospital Chowk", 4, 1.30f));
        graph[318].add(new Edge("Jubilee Baug", 4, 0.28f));
        graph[162].add(new Edge("Trikon Baug", 4, 0.55f));
        graph[79].add(new Edge("Malaviya Chowk", 4, 0.75f));
        graph[28].add(new Edge("Ramkrushna Aashram", 4, 0.60f));
        graph[2].add(new Edge("Hemu Gadhvi Hall", 4, 0.85f));
        graph[202].add(new Edge("Astron Chowk", 4, 0.35f));
        graph[193].add(new Edge("Swaminarayan Mandir / Mahila College Chowk", 4, 0.90f));
        graph[35].add(new Edge("Indubai Mahasatiji Chowk", 4, 1.70f));
        graph[33].add(new Edge("K.K.V. Hall", 4, 1.00f));
        graph[372].add(new Edge("Atmiya College/Central School", 4, 0.75f));
        graph[145].add(new Edge("Crystal Mall", 4, 0.35f));
        graph[207].add(new Edge("Vrundavan Society", 4, 8.80f));
        graph[61].add(new Edge("A.G. Society", 4, 9.90f));
        graph[291].add(new Edge("Everest Park", 4, 0.80f));
        graph[334].add(new Edge("Mota Mava", 4, 2.60f));
        graph[337].add(new Edge("Cosmoplex Cinema", 4, 3.30f));
        graph[251].add(new Edge("Kankot Kalwad Road", 4, 0.70f));
        graph[246].add(new Edge("Vruksh Mandir", 4, 0.70f));
        graph[310].add(new Edge("Uma P.T.C. College", 4, 0.90f));
        graph[373].add(new Edge("Mukhyamantri Aavas Yogna Quater", 4, 1.40f));
        graph[233].add(new Edge("Haripar Gam", 4, 3.30f));
        graph[374].add(new Edge("W.P. Engineering College", 4, 1.70f));
        graph[303].add(new Edge("Virda Vajdi Gam", 4, 1.10f));
        graph[375].add(new Edge("Vagudad VadVajdi Gam", 4, 6.00f));
        graph[41].add(new Edge("G.I.D.C. Gate 1", 4, 5.50f));
        graph[48].add(new Edge("G.I.D.C. Gate 2", 4, 0.15f));
        graph[50].add(new Edge("G.I.D.C. Gate 3", 4, 0.70f));

        // Route - 5

        graph[119].add(new Edge("Aalap Green City", 5, 4.20f));
        graph[55].add(new Edge("Bapa Sitaram Chowk", 5, 0.75f));
        graph[4].add(new Edge("Raiya Chokdi", 5, 5.50f));
        graph[317].add(new Edge("Hanuman Madhi", 5, 3.80f));
        graph[226].add(new Edge("Alkapuri", 5, 0.50f));
        graph[43].add(new Edge("Aazad Chowk", 5, 0.50f));
        graph[351].add(new Edge("Aamrapali Fatak", 5, 0.28f));
        graph[174].add(new Edge("Kishanpara Chowk", 5, 0.90f));
        graph[271].add(new Edge("Jilla Panchayat Chowk", 5, 0.55f));
        graph[75].add(new Edge("Pulchhab Chowk", 5, 0.30f));
        graph[263].add(new Edge("Chitralekha Chowk", 5, 0.40f));
        graph[31].add(new Edge("Limda Chowk", 5, 0.27f));
        graph[240].add(new Edge("Trikon Baug", 5, 0.17f));
        graph[162].add(new Edge("S.T. Bus Stand", 5, 0.85f));
        graph[3].add(new Edge("Kanta Stri Vikash Gruh", 5, 0.85f));
        graph[60].add(new Edge("Bhaktinagar Circle", 5, 0.60f));
        graph[123].add(new Edge("Sheth High school", 5, 0.40f));
        graph[296].add(new Edge("Kothariya Coloni", 5, 0.35f));
        graph[235].add(new Edge("Sorthiya Vadi Circle", 5, 0.28f));
        graph[82].add(new Edge("Jangleshwer Crossing/ Bapunagar", 5, 0.65f));
        graph[59].add(new Edge("Aaji G.I.D.C.", 5, 1.50f));
        graph[237].add(new Edge("Field Marshal Chowk", 5, 0.85f));
        graph[57].add(new Edge("Government Polytechnic", 5, 1.50f));
        graph[215].add(new Edge("AajiDam", 5, 0.50f));
        graph[301].add(new Edge("Mahika Patiyu", 5, 5.10f));
        graph[253].add(new Edge("kalipat", 5, 5.40f));
        graph[305].add(new Edge("R.K. University", 5, 2.60f));
        graph[38].add(new Edge("Tramba Gam", 5, 2.80f));
        
        graph[55].add(new Edge("Raiya Gam", 5, 4.20f));
        graph[4].add(new Edge("Aalap Green City", 5, 0.75f));
        graph[317].add(new Edge("Bapa Sitaram Chowk", 5, 5.50f));
        graph[226].add(new Edge("Raiya Chokdi", 5, 3.80f));
        graph[43].add(new Edge("Hanuman Madhi", 5, 0.50f));
        graph[351].add(new Edge("Alkapuri", 5, 0.50f));
        graph[174].add(new Edge("Aazad Chowk", 5, 0.28f));
        graph[271].add(new Edge("Aamrapali Fatak", 5, 0.90f));
        graph[75].add(new Edge("Kishanpara Chowk", 5, 0.55f));
        graph[263].add(new Edge("Jilla Panchayat Chowk", 5, 0.30f));
        graph[31].add(new Edge("Pulchhab Chowk", 5, 0.40f));
        graph[240].add(new Edge("Chitralekha Chowk", 5, 0.27f));
        graph[162].add(new Edge("Limda Chowk", 5, 0.17f));
        graph[3].add(new Edge("Trikon Baug", 5, 0.85f));
        graph[60].add(new Edge("S.T. Bus Stand", 5, 0.85f));
        graph[123].add(new Edge("Kanta Stri Vikash Gruh", 5, 0.60f));
        graph[296].add(new Edge("Bhaktinagar Circle", 5, 0.40f));
        graph[235].add(new Edge("Sheth High school", 5, 0.35f));
        graph[82].add(new Edge("Kothariya Coloni", 5, 0.28f));
        graph[59].add(new Edge("Sorthiya Vadi Circle", 5, 0.65f));
        graph[237].add(new Edge("Jangleshwer Crossing/ Bapunagar", 5, 1.50f));
        graph[57].add(new Edge("Aaji G.I.D.C.", 5, 0.85f));
        graph[215].add(new Edge("Field Marshal Chowk", 5, 1.50f));
        graph[301].add(new Edge("Government Polytechnic", 5, 0.50f));
        graph[253].add(new Edge("AajiDam", 5, 5.10f));
        graph[305].add(new Edge("Mahika Patiyu", 5, 5.40f));
        graph[38].add(new Edge("kalipat", 5, 2.60f));
        graph[115].add(new Edge("R.K. University", 5, 2.80f));

        // Route - 6
        graph[346].add(new Edge("Santoshinagar", 6, 0.55f));
        graph[69].add(new Edge("Railnagar", 6, 1.60f));
        graph[175].add(new Edge("Central Ware House", 6, 0.90f));
        graph[274].add(new Edge("Popatpara", 6, 0.55f));
        graph[167].add(new Edge("Popatpara Central Jail", 6, 0.95f));
        graph[198].add(new Edge("Junction Railway Station", 6, 1.90f));
        graph[96].add(new Edge("I.P. Mission School", 6, 1.50f));
        graph[195].add(new Edge("Hospital Chowk", 6, 0.60f));
        graph[107].add(new Edge("Jubilee Baug", 6, 0.50f));
        graph[318].add(new Edge("Trikon Baug", 6, 0.50f));
        graph[162].add(new Edge("S.T. Bus Stand", 6, 0.80f));
        graph[3].add(new Edge("Kadvibai School", 6, 1.10f));
        graph[134].add(new Edge("Bhaktinagar Circle", 6, 0.95f));
        graph[123].add(new Edge("Sheth High school", 6, 0.40f));
        graph[296].add(new Edge("Kothariya Coloni", 6, 0.35f));
        graph[235].add(new Edge("Sorthiya Vadi Circle", 6, 0.30f));
        graph[82].add(new Edge("Jangleshwer Crossing/ Bapunagar", 6, 0.65f));
        graph[59].add(new Edge("Aaji G.I.D.C.", 6, 1.70f));
        graph[237].add(new Edge("Field Marshal Chowk", 6, 0.85f));
        graph[57].add(new Edge("Government Polytechnic", 6, 1.50f));
        graph[215].add(new Edge("Aajidam Chokdi", 6, 0.50f));
        graph[86].add(new Edge("Mansarovar Society", 6, 0.35f));
        graph[265].add(new Edge("Aarti Industrial Area", 6, 1.80f));
        graph[252].add(new Edge("Thebchada Mahika Patiyu", 6, 4.20f));
        graph[376].add(new Edge("Krishna International School", 6, 11.40f));
        graph[329].add(new Edge("kalipat", 6, 14.90f));
        graph[305].add(new Edge("R.K. University", 6, 2.70f));
        graph[38].add(new Edge("Bharad Engineering College", 6, 1.30f));
        graph[306].add(new Edge("Tramba Gam", 6, 1.60f));

        graph[69].add(new Edge("Santoshinagar Railway Crossing", 6, 0.55f));
        graph[175].add(new Edge("Santoshinagar", 6, 1.60f));
        graph[274].add(new Edge("Central Ware House", 6, 0.90f));
        graph[167].add(new Edge("Central Ware House", 6, 0.55f));
        graph[198].add(new Edge("Popatpara", 6, 0.95f));
        graph[96].add(new Edge("Popatpara Central Jail", 6, 1.90f));
        graph[195].add(new Edge("Junction Railway Station", 6, 1.50f));
        graph[107].add(new Edge("I.P. Mission School", 6, 0.60f));
        graph[318].add(new Edge("Hospital Chowk", 6, 0.50f));
        graph[162].add(new Edge("Jubilee Baug", 6, 0.50f));
        graph[3].add(new Edge("Trikon Baug", 6, 0.80f));
        graph[134].add(new Edge("S.T. Bus Stand", 6, 1.10f));
        graph[123].add(new Edge("Kadvibai School", 6, 0.95f));
        graph[296].add(new Edge("Bhaktinagar Circle", 6, 0.40f));
        graph[235].add(new Edge("Sheth High school", 6, 0.35f));
        graph[82].add(new Edge("Kothariya Coloni", 6, 0.30f));
        graph[59].add(new Edge("Sorthiya Vadi Circle", 6, 0.65f));
        graph[237].add(new Edge("Jangleshwer Crossing/ Bapunagar", 6, 1.70f));
        graph[57].add(new Edge("Aaji G.I.D.C.", 6, 0.85f));
        graph[215].add(new Edge("Field Marshal Chowk", 6, 1.50f));
        graph[86].add(new Edge("Government Polytechnic", 6, 0.50f));
        graph[265].add(new Edge("Aajidam Chokdi", 6, 0.35f));
        graph[252].add(new Edge("Mansarovar Society", 6, 1.80f));
        graph[376].add(new Edge("Aarti Industrial Area", 6, 4.20f));
        graph[329].add(new Edge("Thebchada Mahika Patiyu", 6, 11.40f));
        graph[305].add(new Edge("Krishna International School", 6, 14.90f));
        graph[38].add(new Edge("R.K. University", 6, 2.70f));
        graph[306].add(new Edge("Bharad Engineering College", 6, 1.30f));
        graph[115].add(new Edge("Tramba Gam", 6, 1.60f));

        // Route - 7

        graph[104].add(new Edge("Punitnagar", 7, 10.00f));
        graph[270].add(new Edge("Bajrangvadi Circle", 7, 10.00f));
        graph[100].add(new Edge("Lakhno Bunglow", 7, 8.60f));
        graph[102].add(new Edge("Jivantika Main Road Crossing", 7, 0.24f));
        graph[249].add(new Edge("Ramapir Chokdi", 7, 1.10f));
        graph[116].add(new Edge("Nanavati Chowk", 7, 0.65f));
        graph[317].add(new Edge("Raiya Chokdi", 7, 5.70f));
        graph[206].add(new Edge("Bramh Samaj", 7, 1.10f));
        graph[226].add(new Edge("Hanuman Madhi", 7, 0.80f));
        graph[43].add(new Edge("Alkapuri", 7, 0.35f));
        graph[351].add(new Edge("Aazad Chowk", 7, 0.45f));
        graph[174].add(new Edge("Aamrapali Fatak", 7, 0.28f));
        graph[271].add(new Edge("Kishanpara Chowk", 7, 0.90f));
        graph[75].add(new Edge("Jilla Panchayat Chowk", 7, 0.55f));
        graph[263].add(new Edge("Pulchhab Chowk", 7, 0.30f));
        graph[31].add(new Edge("Chitralekha Chowk", 7, 0.50f));
        graph[240].add(new Edge("Limda Chowk", 7, 0.17f));
        graph[162].add(new Edge("Trikon Baug", 7, 0.80f));
        graph[3].add(new Edge("S.T. Bus Stand", 7, 1.30f));
        graph[98].add(new Edge("Aaryasamaj", 7, 2.00f));
        graph[60].add(new Edge("Kanta Stri Vikash Gruh", 7, 0.60f));

        graph[270].add(new Edge("Bajrangvadi Circle", 7, 10.00f));
        graph[100].add(new Edge("Punitnagar", 7, 8.60f));
        graph[102].add(new Edge("Lakhno Bunglow", 7, 0.24f));
        graph[249].add(new Edge("Jivantika Main Road Crossing", 7, 1.10f));
        graph[116].add(new Edge("Ramapir Chokdi", 7, 0.65f));
        graph[317].add(new Edge("Nanavati Chowk", 7, 5.70f));
        graph[206].add(new Edge("Raiya Chokdi", 7, 1.10f));
        graph[226].add(new Edge("Bramh Samaj", 7, 0.80f));
        graph[43].add(new Edge("Hanuman Madhi", 7, 0.35f));
        graph[351].add(new Edge("Alkapuri", 7, 0.45f));
        graph[174].add(new Edge("Aazad Chowk", 7, 0.28f));
        graph[271].add(new Edge("Aamrapali Fatak", 7, 0.90f));
        graph[75].add(new Edge("Kishanpara Chowk", 7, 0.55f));
        graph[263].add(new Edge("Jilla Panchayat Chowk", 7, 0.30f));
        graph[31].add(new Edge("Pulchhab Chowk", 7, 0.50f));
        graph[240].add(new Edge("Chitralekha Chowk", 7, 0.27f));
        graph[162].add(new Edge("Limda Chowk", 7, 0.17f));
        graph[3].add(new Edge("Trikon Baug", 7, 0.80f));
        graph[98].add(new Edge("S.T. Bus Stand", 7, 1.30f));
        graph[60].add(new Edge("Aaryasamaj", 7, 2.00f));
        graph[123].add(new Edge("Kanta Stri Vikash Gruh", 7, 0.60f));

        // Route - 8

        graph[23].add(new Edge("Marutinagar 50 Feet Road Chowk", 8, 7.60f));
        graph[330].add(new Edge("Gurudev Park", 8, 7.00f));
        graph[165].add(new Edge("Ranchhod Aashram", 8, 1.30f));
        graph[56].add(new Edge("Parevadi Chowk", 8, 1.00f));
        graph[148].add(new Edge("I.P. Mission School", 8, 0.60f));
        graph[195].add(new Edge("Hospital Chowk", 8, 0.50f));
        graph[107].add(new Edge("Jubilee Baug", 8, 5.50f));
        graph[318].add(new Edge("Trikon Baug", 8, 0.80f));
        graph[162].add(new Edge("S.T. Bus Stand", 8, 1.20f));
        graph[3].add(new Edge("Kadvibai School", 8, 2.30f));
        graph[98].add(new Edge("Makkam Chowk", 8, 0.65f));
        graph[134].add(new Edge("Aanand Bunglows", 8, 1.10f));
        graph[158].add(new Edge("Mavdi Fire Station", 8, 0.45f));
        graph[168].add(new Edge("Fuliya Hanuman Mandir", 8, 0.23f));
        graph[77].add(new Edge("Mavdi Chowk", 8, 0.60f));
        graph[225].add(new Edge("Bapa Sitaram Chowk", 8, 0.65f));
        graph[338].add(new Edge("Mavdi Gam", 8, 2.50f));
        graph[4].add(new Edge("Dream City", 8, 1.50f));
        graph[345].add(new Edge("Jetko Chokdi", 8, 2.50f));
//        graph[260].add(new Edge("Labhubhai Engineering College", 8, 0.70f));
        graph[84].add(new Edge("Government Engineering College", 8, 2.50f));
        graph[87].add(new Edge("Labhubhai Engineering college", 8, 0.70f));

        graph[330].add(new Edge("Greenland Chokdi", 8, 0.75f));
        graph[165].add(new Edge("Marutinagar 50 Feet Road Chowk", 8, 7.60f));
        graph[56].add(new Edge("Gurudev Park", 8, 7.00f));
        graph[148].add(new Edge("Ranchhod Aashram", 8, 1.30f));
        graph[195].add(new Edge("Parevadi Chowk", 8, 1.00f));
        graph[107].add(new Edge("I.P. Mission School", 8, 0.60f));
        graph[318].add(new Edge("Hospital Chowk", 8, 0.50f));
        graph[162].add(new Edge("Jubilee Baug", 8, 5.50f));
        graph[3].add(new Edge("Trikon Baug", 8, 0.80f));
        graph[98].add(new Edge("S.T. Bus Stand", 8, 1.20f));
        graph[134].add(new Edge("Aaryasamaj", 8, 2.30f));
        graph[158].add(new Edge("Kadvibai School", 8, 0.65f));
        graph[168].add(new Edge("Makkam Chowk", 8, 1.10f));
        graph[77].add(new Edge("Aanand Bunglows", 8, 0.45f));
        graph[225].add(new Edge("Mavdi Fire Station", 8, 0.23f));
        graph[338].add(new Edge("Fuliya Hanuman Mandir", 8, 0.60f));
        graph[4].add(new Edge("Mavdi Chowk", 8, 0.65f));
        graph[345].add(new Edge("Bapa Sitaram Chowk", 8, 0.65f));
        graph[260].add(new Edge("Mavdi Gam", 8, 2.50f));
        graph[84].add(new Edge("Dream City", 8, 1.50f));
        graph[87].add(new Edge("Jetko Chokdi", 8, 2.50f));
        graph[151].add(new Edge("Government Engineering College", 8, 0.70f));
        graph[87].add(new Edge("Labhubhai Engineering College", 8, 0.70f));

        // Route - 9
        graph[266].add(new Edge("Darshan Eng. College", 9, 1.50f));
        graph[1].add(new Edge("Ratanpar (Ramji Mandir)", 9, 2.80f));
        graph[256].add(new Edge("Ratanpar gam", 9, 0.17f));
        graph[323].add(new Edge("Ratanpar Telephone Exchange", 9, 1.00f));
        graph[220].add(new Edge("Gauridal", 9, 1.90f));
        graph[164].add(new Edge("I.O.C.", 9, 1.10f));
        graph[360].add(new Edge("Marwadi College", 9, 3.60f));
        graph[39].add(new Edge("Bedi Marketing Yard", 9, 3.80f));
        graph[47].add(new Edge("Bedi", 9, 0.90f));
        graph[49].add(new Edge("150 Feet Jamnagar Road Crossing", 9, 0.65f));
        graph[182].add(new Edge("Mukhyamantri Aavas Yogna Quater", 9, 5.20f));
        graph[106].add(new Edge("Aastha Sangrila", 9, 3.20f));
        graph[25].add(new Edge("Krishna Banglowz-3 (Sadhuvasvani Kunj Road Crossing)", 9, 4.00f));
        graph[99].add(new Edge("Manhar Pura (150 ft. Ring Road)", 9, 5.30f));
        graph[8].add(new Edge("Madhapar Chowk", 9, 6.30f));
        graph[70].add(new Edge("Vora Society", 9, 0.55f));
        graph[76].add(new Edge("Gaytridham", 9, 4.20f));
        graph[136].add(new Edge("Vankaner Society", 9, 3.60f));
        graph[171].add(new Edge("Bajrangvadi", 9, 0.50f));
        graph[324].add(new Edge("Railway Colony", 9, 1.20f));
        graph[280].add(new Edge("Bhomeshvar", 9, 1.60f));
        graph[287].add(new Edge("Special School For Boys", 9, 0.35f));
        graph[314].add(new Edge("Ruda Office", 9, 0.45f));
        graph[311].add(new Edge("Hospital Chowk", 9, 1.60f));
        graph[107].add(new Edge("Jubilee Baug", 9, 0.50f));
        graph[318].add(new Edge("Trikon Baug", 9, 0.55f));
        graph[162].add(new Edge("Malaviya Chowk", 9, 0.65f));
        graph[79].add(new Edge("Ramkrushna Aashram", 9, 0.50f));
        graph[28].add(new Edge("Jilla Panchayat Chowk", 9, 1.20f));
        graph[75].add(new Edge("Kishanpara Chowk", 9, 0.65f));
        graph[271].add(new Edge("Indubai Mahasatiji Chowk", 9, 2.10f));
        graph[35].add(new Edge("K.K.V. Hall", 9, 1.50f));
        graph[33].add(new Edge("Crystal Mall", 9, 1.10f));
        graph[145].add(new Edge("A.G. Society", 9, 0.60f));
        graph[61].add(new Edge("Sarita Vihar", 9, 1.70f));
        graph[247].add(new Edge("Saurastra University", 9, 2.70f));

        graph[1].add(new Edge("Arpit Eng. College (Hadala Gam)", 9, 1.50f));
        graph[256].add(new Edge("Darshan Eng. College", 9, 2.80f));
        graph[323].add(new Edge("Ratanpar gam", 9, 0.17f));
        graph[220].add(new Edge("Ratanpar Telephone Exchange", 9, 1.00f));
        graph[164].add(new Edge("Gauridal", 9, 1.90f));
        graph[360].add(new Edge("I.O.C.", 9, 1.10f));
        graph[39].add(new Edge("Marwadi College", 9, 3.60f));
        graph[47].add(new Edge("Bedi Marketing Yard", 9, 3.80f));
        graph[49].add(new Edge("Bedi", 9, 0.90f));
        graph[182].add(new Edge("150 Feet Jamnagar Road Crossing", 9, 0.65f));
        graph[106].add(new Edge("Mukhyamantri Aavas Yogna Quater", 9, 5.20f));
        graph[25].add(new Edge("Aastha Sangrila", 9, 3.20f));
        graph[8].add(new Edge("Manhar Pura (150 ft. Ring Road)", 9, 4.00f));
        graph[70].add(new Edge("Madhapar Chowk", 9, 5.30f));
        graph[76].add(new Edge("Vora Society", 9, 6.30f));
        graph[136].add(new Edge("Gaytridham", 9, 0.55f));
        graph[171].add(new Edge("Vankaner Society", 9, 4.20f));
        graph[324].add(new Edge("Bajrangvadi", 9, 3.60f));
        graph[280].add(new Edge("Railway Colony", 9, 0.50f));
        graph[287].add(new Edge("Bhomeshvar", 9, 1.20f));
        graph[314].add(new Edge("Special School For Boys", 9, 1.60f));
        graph[311].add(new Edge("Ruda Office", 9, 0.35f));
        graph[107].add(new Edge("Hospital Chowk", 9, 0.45f));
        graph[318].add(new Edge("Jubilee Baug", 9, 1.60f));
        graph[162].add(new Edge("Trikon Baug", 9, 0.50f));
        graph[79].add(new Edge("Malaviya Chowk", 9, 0.55f));
        graph[28].add(new Edge("Ramkrushna Aashram", 9, 0.65f));
        graph[75].add(new Edge("Jilla Panchayat Chowk", 9, 0.50f));
        graph[271].add(new Edge("Kishanpara Chowk", 9, 1.20f));
        graph[35].add(new Edge("Indubai Mahasatiji Chowk", 9, 0.65f));
        graph[33].add(new Edge("K.K.V. Hall", 9, 2.10f));
        graph[145].add(new Edge("Crystal Mall", 9, 1.50f));
        graph[61].add(new Edge("A.G. Society", 9, 1.10f));
        graph[247].add(new Edge("Sarita Vihar", 9, 0.60f));
        graph[114].add(new Edge("Saurastra University", 9, 1.70f));
        

    }

    public static List<String> findShortestPath(List<Edge>[] graph, Map<String, Integer> stationIndices, String src, String tar) {
        Map<String, Float> distance = new HashMap<>();
        Map<String, String> previous = new HashMap<>();
        PriorityQueue<String> queue = new PriorityQueue<>(Comparator.comparing(distance::get));

        distance.put(src, 0.0f);
        queue.add(src);

        while (!queue.isEmpty()) {
            String u = queue.poll();
            if (u.equals(tar)) {
                break;
            }

            int uIndex;
            if (stationIndices.containsKey(u)) {
                uIndex = stationIndices.get(u);
            } else {
                System.out.println("Station '" + u + "' is not Found.");
                List<String> available = Arrays.asList("Station '" + u + "' is not Found.");
                return available ;
            }


            for (Edge edge : graph[uIndex]) {
                String v = edge.Destination;
                float alt = distance.get(u) + edge.distance;
                if (alt < distance.getOrDefault(v, Float.MAX_VALUE)) {
                    distance.put(v, alt);
                    previous.put(v, u);
                    queue.add(v);
                }
            }
        }

        List<String> path = new ArrayList<>();
        String current = tar;
        while (current != null) {
            path.add(current);
            current = previous.get(current);
        }
        Collections.reverse(path);

        return path.size() > 1 ? path : Collections.emptyList();
    }

    public static void main(String[] args) {
        List<Edge>[] graph = new List[377];
        for (int i = 0; i < graph.length; i++) {
            graph[i] = new ArrayList<Edge>();
        }
        Map<String, Integer> stationIndices = new HashMap<>();
        createGraph(graph, stationIndices);
    
        String src = getSrc();
        String tar = getTar();
    
        // Check if the source and target stations exist
        if (!stationIndices.containsKey(src) || !stationIndices.containsKey(tar)) {
            System.out.println("One or both of the specified stations are not found.");
        } else {
            List<String> shortestPath = findShortestPath(graph, stationIndices, src, tar);
    
            if (shortestPath.isEmpty()) {
                System.out.println("No path available.");
            } else {
                System.out.println("Shortest Path:");
                float totalDistance = 0.0f;
                String prevStation = shortestPath.get(0);
                for (String station : shortestPath) {
                    int prevIndex = stationIndices.get(prevStation);
//                    int currentIndex = stationIndices.get(station);
                    for (Edge edge : graph[prevIndex]) {
                        if (edge.Destination.equals(station)) {
                            String routeDescription = (edge.Route == 0) ? "BRTS" : "R-" + edge.Route;
                            System.out.println(routeDescription + " : " + prevStation);
                            totalDistance += edge.distance;
                        }
                    }
                    prevStation = station;
                }
                System.out.println("Length: " + totalDistance + " km");
            }
        }
    }    
}
