public class Print {
    public static void main(String[] args) {
        String[] locations = {
            "Madhapar Chowk",
            "Ayodhya Park Chowk",
            "Shital Park",
            "Ramdevpir Chowk",
            "Nanavati Chowk",
            "Raiya Chowk",
            "Raiya TelePhone Exchange",
            "Indira Circle",
            "West Zone Office",
            "Nana Mava Chowk",
            "Maha Puja Dham Chowk",
            "Om Nagar Chowk",
            "Mavdi Chowk",
            "Umiya Chowk",
            "Ambedkar Chowk",
            "Goverdhan Chowk",
            "Punit Nagar Chowk",
            "Gondal Chowk",
            "Saurastra University",
            "BT Savani (Kidni) Hospital",
            "Akashvani Chowk",
            "Panchayat Nagar Chowk",
            "Indubai Mahasatiji Chowk",
            "Swaminarayan Mandir / Mahila",
            "Astron Chowk",
            "Hemu Gadhvi Hall",
            "Ramkrushna Aashram",
            "Malaviya Chowk",
            "Trikon Baug",
            "HN Shukla College",
            "Pradyumna Park",
            "Marketing Yard",
            "Bhagirath Society",
            "Lakheshvar Society - R.T.O. Office",
            "GramUdhyog Mandir Pedak",
            "Setelite Chowk - Maruti Nagar Approch Road",
            "Aayaknagar - Pedak Road",
            "Narayan Nagar Aproch Road - Govind Nagar",
            "Champak Nagar - Panino Ghodo",
            "Patel Vadi",
            "Parevadi Chowk",
            "Hospital Chowk",
            "Jubilee Baug",
            "Kothicompound",
            "Junction Railway Station",
            "Popatpara Central Jail",
            "Popatpara",
            "Central Ware House",
            "AajiDam",
            "Government Polytechnic",
            "Field Marshal Chowk",
            "Sarvoday Society",
            "Udhyog Nagar",
            "Chunarvad Chowk",
            "R.M.C East Zone Office",
            "Manhar Pura/Bedinaka Fire Station",
            "Jalaram Chowk (Santkabir Road no Khuno)",
            "Aajidam Chokdi",
            "Mansarovar Society",
            "Aarti Industrial Area",
            "Thebchada Mahika Patiyu",
            "Krishna International School",
            "kalipat",
            "R.K. University",
            "Tramba Gam",
            "Santoshinagar Railway Crossing",
            "Santoshinagar",
            "Railnagar",
            "Central Ware House",
            "Popatpara",
            "Jangleshwer Crossing/ Bapunagar",
            "Aaji G.I.D.C.",
            "Field Marshal Chowk",
            "Government Polytechnic",
            "AajiDam",
            "Mahika Patiyu",
            "kalipat",
            "R.K. University",
            "Bharad Engineering College",
            "Tramba Gam",
            "Bajrangvadi Circle",
            "Punitnagar",
            "Lakhno Bunglow",
            "Jivantika Main Road Crossing",
            "Ramapir Chokdi",
            "Bramh Samaj",
            "Government Engineering College",
            "Labhubhai Engineering college",
            "Arpit Eng. College (Hadala Gam)",
            "Darshan Eng. College",
            "Ratanpar (Ramji Mandir)",
            "Ratanpar gam",
            "Ratanpar Telephone Exchange",
            "Gauridal",
            "I.O.C.",
            "Marwadi College",
            "Bedi Marketing Yard",
            "Bedi",
            "150 Feet Jamnagar Road Crossing",
            "Mukhyamantri Aavas Yogna Quarter",
            "Aastha Sangrila",
            "Krishna Banglowz-3 (Sadhuvasvani Kunj Road Crossing)",
            "Manhar Pura (150 ft. Ring Road)",
            "Vora Society",
            "Gaytridham",
            "Vankaner Society",
            "Bajrangvadi",
            "Railway Colony",
            "Bhomeshvar",
            "Special School For Boys",
            "Ruda Office",
            "Kadvibai School",
            "Sheth High school",
            "Kothariya Coloni",
            "Sorthiya Vadi Circle",
            "Jangleshwer Crossing/ Bapunagar",
            "Aaji G.I.D.C.",
            "Field Marshal Chowk",
            "Aajidam Chokdi",
            "Mansarovar Society",
            "Aarti Industrial Area",
            "Thebchada Mahika Patiyu",
            "Krishna International School",
            "kalipat",
            "R.K. University",
            "Bharad Engineering College",
            "Tramba Gam" ,
            "Dharmendrasihnji College",
            "Jilla Panchayat Chowk",
            "Kishanpara Chowk",
            "Sadhu Vasvani School" , 
            "Ajanta Park / Janak Puri",
            "Balaji Park / Satellite Park",
            "Aalap Green City",
            "Raiya Gam" ,
            "Jivraj Park",
            "Aarya Land Residency",
            "Jetko Chokdi",
            "Dream City",
            "Mavdi Gam",
            "Fuliya Hanuman Mandir",
            "Mavdi Fire Station",
            "Aanand Bunglows",
            "Swaminarayan Chowk",
            "P. D. M. College",
            "Gurukul",
            "Bhaktinagar Circle",
            "Kanta Stri Vikash Gruh",
            "S.T. Bus Stand",
            "I.P. Mission School",
            "Bhaktinagar Park",
            "Swaminarayan Mandir / Mahila College Chowk",
            "K.K.V. Hall",
            "Atmiya College/Central School",
            "Crystal Mall",
            "Vrundavan Society",
            "A.G. Society",
            "Everest Park",
            "Mota Mava",
            "Cosmoplex Cinema",
            "Kankot Kalwad Road",
            "Vruksh Mandir",
            "Uma P.T.C. College",
            "Haripar Gam",
            "W.P. Engineering College",
            "Virda Vajdi Gam",
            "Vagudad VadVajdi Gam",
            "G.I.D.C. Gate 1",
            "G.I.D.C. Gate 2",
            "G.I.D.C. Gate 3" ,
            "Bapa Sitaram Chowk",
            "Raiya Chokdi",
            "Hanuman Madhi",
            "Alkapuri",
            "Aazad Chowk",
            "Aamrapali Fatak",
            "Pulchhab Chowk",
            "Chitralekha Chowk",
            "Limda Chowk" , 
            "Aaryasamaj" , 
            "Greenland Chokdi",
            "Marutinagar 50 Feet Road Chowk",
            "Gurudev Park",
            "Ranchhod Aashram",
            "Makkam Chowk" ,
            "Sarita Vihar"
        };

//         String[] Route  = {
//             "Madhapar Chowk",
//             "Ayodhya Park Chowk",
//             "Shital Park",
//             "Ramdevpir Chowk",
//             "Nanavati Chowk",
//             "Raiya Chowk",
//             "Raiya TelePhone Exchange",
//             "Indira Circle",
//             "West Zone Office",
//             "Nana Mava Chowk",
//             "Maha Puja Dham Chowk",
//             "Om Nagar Chowk",
//             "Mavdi Chowk",
//             "Umiya Chowk",
//             "Ambedkar Chowk",
//             "Goverdhan Chowk",
//             "Punit Nagar Chowk",
//             "Gondal Chowk"
//         };

//         float[] Distance = {
//             0.6f , 
//             0.65f ,
//             0.9f ,
//             0.75f ,
//             0.55f,
//             1.2f ,
//             0.8f ,
//             1.4f ,
//             0.65f ,
//             0.7f ,
//             0.5f ,
//             0.55f ,
//             0.7f,
//             0.5f,
//             0.6f,
//             0.75f
//         };
// //      graph[70].add(new Edge("Ayodhya Park Chowk", 0, 0.6f));
//         for(int i = 1 ; i< Route.length; i++ ) {

//             int index = -1 ;
//             for(int j = 0 ; j < locations.length - 1 ; j++) {
//                 if(locations[j].equals(Route[i - 1])) {
//                     index = j ;
//                 }
//             }

//             System.out.println("graph[" + index + "].add(new Edge(\"" + Route[i] + "\", 0, " + Distance[i] + "));");


//         }

// station.put(0, "Jivraj Park");

for(int i = 0 ;i<locations.length ; i++) {
    System.out.println("station.put(\"" + locations[i] + "\"," + i + ");");
}
    }
}
